### ISSUE TITLE
WP affords treatment of the publication as a logical whole

### ISSUE THREAD

**Issue by TzviyaSiegman** [w3c/wpub#136]
[2.1.7 Single Unit](https://www.w3.org/TR/pwp-ucr/#single)
User agents must treat a Web Publication as a single logical resource with its own URL, beyond the references to individual, constituent resources.
Picking up on #52 

Also related to
* is a canonical identifier necessary https://github.com/w3c/wpub/issues/58
* How do we identify a web publication and its components? https://github.com/w3c/wpub/issues/5

**Comment by HadrienGardeur** [comment]
How does this affect specific affordances? 

This is IMO a weird one, because this is mostly conceptual and doesn't tie directly to its own affordance. I would recommend dropping the affordances tag or closing this issue.

**Comment by iherman** [comment]
I would actually be in favor dropping this issue. The whole draft starts by establishing what we are working on, ie, a set of web resources handled as one unit. This issue does not really add anything to that.

The only point with this issue is that, at some point, we may want to add some references to the Use Case document, and this statement comes from [on of the documented entries in the UCR](https://w3c.github.io/dpub-pwp-ucr/#r_single). Ie, we will have to put a backward reference to it. But I do not think it is worth keeping this issue open for that purpose.

**Comment by iherman** [comment]
@TzviyaSiegman would you agree closing this issue?

**Comment by TzviyaSiegman** [comment]
+1
