### ISSUE TITLE
WP affords guided navigation

### ISSUE THREAD

**Issue by TzviyaSiegman** [w3c/wpub#139]
[2.2.1 Default Reading Order](https://www.w3.org/TR/pwp-ucr/#reading-order)
There should be a means to indicate the author’s preferred navigation structure among the resources of a Web Publication.

picking up on #52 
This is addressed in the current draft in the info-set section about [structural properties](https://w3c.github.io/wpub/#infoset-structure), which currently has:
* Default reading order (required)
* Resouce list (required)
* Table of contents (recommended)

**Comment by HadrienGardeur** [comment]
In the draft this is also handled in two different sections, specifically about affordances:

- [Reading Order](https://w3c.github.io/wpub/#aff-reading-order)
- [Table of Contents](https://w3c.github.io/wpub/#aff-toc)

**Comment by HadrienGardeur** [comment]
It's also worth pointing out that in the context of EPUB, we mostly used the term "guided navigation" to panel by panel navigation for comics.

It's unclear at this point if this group will also address this requirement (or if we'll have an equivalent at all for FXL).

**Comment by jmulliken** [comment]
Could this be combined with TOC or Reading Order by saying WP affords automated reading order if no prescribed navigation is provided?

**Comment by WSchindler** [comment]
Affordance name: **Guided navigation (#139)**
 
**1. Short description:** 
The author should be able to define a preferred navigation across the (primary?) resources of a Web 
Publication. 
From the perspective of a UA this would be the **default reading order** which defines the sequence in which to present the resources of the Web Publication to the user. A **Table of Contents** may expose that order explicitly to the user.

**2. Dependencies:** 
The preferred navigation would be defined in terms of a _**default reading order**_ which must be a required item of the manifest. It is based on a list of WP resources which contains all internal resources and may also list external resources. This **list of resources** should as well be a required item of the manifest.

_aside: The UA needs to be able to quickly identify and locate the resources that are part of the logical unit of a WP. The preferred navigation would typically only define an ordering of the major building blocks/resources -  however we dub these. I would suppose that references to external resources that are not part of WP would not be part of the preferred navigation._ 

**3. Use case Reference:**
_Web Publications Use Cases and Requirements: W3C Interest Group Note 02 May 2017_
**2.2.1 Default Reading Order**
[https://www.w3.org/TR/pwp-ucr/#reading-order](url)

Req. 12: There should be a means to indicate the author’s preferred navigation structure among the resources of a Web Publication.
A user agent needs to know the sequence in which to present components of a Web Publication to the user, including the starting point.

**4. Examples:** 
_Example 1 (quoted from UCR):_
Moby Dick contains 136 chapters. Each chapter is a separate HTML document, with a logical order for reading them. It should be possible for the publication to inform the user agent that the proper order for consumption of the HTML documents is sequentially, starting by the first chapter.

_Example 2:_
Martina is consuming a scientific book - a well-known introductory overview of a specific topic (e.g. UX) - for her senior thesis. The author has taken great care to explain first the basic concepts and then the theoretic approaches step by step in subsequent chapters which logically build upon each other so that the reader is supposed to master the contents of the previous chapters. For a novice to that subject, it is strongly recommended to follow the default reading order laid down by the author.

_Example 3:_
Joan is learning French at school. The schoolbook authors have divided all the stuff to be learned together with appropriate classroom activities across several chapters by defining a learning progression that is adequate for Joan's age and her level of education. In consuming this schoolbook Joan and her teachers should respect this default order of chapters.

**5. Testing:**
If a test user opens up a WP in a WP-aware UA,  he or she should have a means to detect and follow the default reading order.
By inspecting the manifest of the WP, a tester should find two items: the default reading order and the list of resources.

**Comment by wareid** [comment]
Affordances addressed in the UCR document, as mentioned in the meeting on Feb 4 2019, I am closing this issue.
