### ISSUE TITLE
WP affords filtered navigation/reading experience

### ISSUE THREAD

**Issue by TzviyaSiegman** [w3c/wpub#140]
[2.2.2 Random Access to Content](https://www.w3.org/TR/pwp-ucr/#random-access)
Authors of a Web Publication should be able to provide the user agent with information to filtered or sub-set parts of the publication. 
picking up on #52

**Comment by HadrienGardeur** [comment]
I'm not sure what this means in terms of affordance.

With a WP, every resource has its own URI and can therefore be reached and displayed.

Does this mean that if a UA renders a resource and discover that it's part of a publication, it shouldn't automatically redirect the user to the start of the WP?

**Comment by TzviyaSiegman** [comment]
@HadrienGardeur This is offering alternative ToCs or a method to access all the absracts in the publication (for example).

**Comment by HadrienGardeur** [comment]
So we're talking about something generated by the UA based on metadata or fragments of the resources listed in the default reading order?

**Comment by jmulliken** [comment]
Is this a non-linear or multi-linear alternative to reading order? Can you give an example?

**Comment by BigBlueHat** [comment]
As long as the format describes the "navigable resources" which are "bound" into the publication (+/- resource-specific metadata), the UA should have what it needs to give "random access" to any individual part or collection of parts built from either metadata or user action (i.e. "these are my favorite chapters").

Essentially, as long as the parts are identifiable individually and as "within the whole," then it should be possible to build a "sub-set" of the publication.

Who does the sub-setting is immaterial--as in, this could be publisher provided "alternative" content indexes or user-built "favorites" or whatever.

The key is that the parts must have "constituent identification" ("this resource is *part of* that resource") or the constituent relationship must be gleaned and *kept* by the UA in order to provide in situ presentation (i.e. Chapter 1 of Moby-Dick as part of the book...and not alone).

**Comment by marisademeglio** [comment]
Affordance name:  filtered navigation

1. Short Description: The WP should afford a fast way to locate sets of items that aren't the primary TOC. The UA should not have to parse this information out of the publication by scanning every content document.

2. Dependencies:  The manifest/infoset should afford easy discovery of these item sets.

3. Use case references: A publication-wide list of images, pagebreaks, or charts are all examples of non-TOC item sets that could be exposed to the UA.

4. Examples:
EPUB3 pagelist 

5. Testing:
UAs may support this feature by offering a sidebar panel containing available item sets.
<img width="620" alt="screen shot 2018-06-18 at 9 12 35 am" src="https://user-images.githubusercontent.com/734730/41550756-a45d7b2e-72de-11e8-9770-221668d338ba.png">

**Comment by wareid** [comment]
Affordances addressed in the UCR document, as mentioned in the meeting on Feb 4 2019, I am closing this issue.
