### ISSUE TITLE
Infoset feedback: Address / Canonical identifier

### ISSUE THREAD

**Issue by laudrain** [w3c/wpub#179]
From [Feedback](https://lists.w3.org/Archives/Public/public-publ-wg/2018Apr/0008.html) from Edge
in **3.2 Infoset requirements**

Address / Canonical identifier: Can we have concrete examples? If there really is need for a canonical identifier that must map to a URL, it should just be a URL.

**Comment by laudrain** [comment]
Example with the existing DOI mechanism :
The publication with the following DOI [doi:10.1392/BC1.0](http://dx.medra.org/10.1392/BC1.0) is presently at the following address: https://www.medra.org/stdoc/casalini_bc_en.pdf.

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2019/2019-03-18-pwg#section2-3).

- No actions or resolutions
<details><summary><i class="differentiate">View the transcript</i></summary>
Infoset feedbacks<br/>
Wendy Reid: Infoset feedback : Accessibility compliance information<br/>
… We’ve expunged Infoset. So close 178, 179, 180, 181?<br/>
… Close 178…181 — all infoset related.<br/>
Wendy Reid: <a href="https://github.com/w3c/wpub/issues/178">https://github.com/w3c/wpub/issues/178</a><br/>
Wendy Reid: <a href="https://github.com/w3c/wpub/issues/179">https://github.com/w3c/wpub/issues/179</a><br/>
Wendy Reid: <a href="https://github.com/w3c/wpub/issues/180">https://github.com/w3c/wpub/issues/180</a><br/>
Wendy Reid: <a href="https://github.com/w3c/wpub/issues/181">https://github.com/w3c/wpub/issues/181</a><br/>
</details>
