### ISSUE TITLE
Sortable metadata strings

### ISSUE THREAD

**Issue by HadrienGardeur** [w3c/wpub#188]
This is based on my gap analysis between EPUB 3.2 and WP: https://github.com/w3c/wpub/issues/176#issuecomment-382634697

EPUB has the concept of a sortable string through the use of `opf:file-as`.

In EPUB 2.x this was limited primarily to [`creator`](http://www.idpf.org/epub/20/spec/OPF_2.0.1_draft.htm#Section2.2.2) and [`contributor`](http://www.idpf.org/epub/20/spec/OPF_2.0.1_draft.htm#Section2.2.6).

EPUB 3.0.x muddle things up since it introduces refines but it's [primarily directed towards `creator` and `contributor`](http://www.idpf.org/epub/301/spec/epub-publications.html#meta-properties-publication) once again.

[The current EPUB 3.2 draft](https://w3c.github.io/publ-epub-revision/epub32/spec/epub-packages.html) is a little bit inconsistent in that regard, but it seems to expand the scope of this attribute:
> Allowed on: dc:contributor, dc:creator, dc:publisher, dc:title and meta.

It's also worth pointing out that Calibre introduced its own element for sorting titles (`calibre:title_sort`), probably because it had a strong use case for it, yet it felt like `opf:file-as` didn't allowed that (which is probably true).

Based on @dauwhe feedback, this might be eventually dropped in EPUB 3.2 but it's worth hearing from the wider community (cc @kovidgoyal, @kevinhendricks) about their need for sortable strings.

Sortable strings are primarily meant for user agents that provide a way for the user to filter and sort their publications based on such strings.

**Comment by kovidgoyal** [comment]
Sortable strings are important for calibre. They are used when sorting on title, authors and series. This is done because there is no foolprof algorithm for generating the correct sort order for these fields, especially since the rules for sorting them vary between cultures. So calibre auto-generates a sort value for a given field but also allows users to override it, as needed.

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2019/2019-03-18-pwg#section2-5).

- No actions or resolutions
<details><summary><i class="differentiate">View the transcript</i></summary>
2.5. Sortable metadata string<br/>
Wendy Reid: <a href="https://github.com/w3c/wpub/issues/188">https://github.com/w3c/wpub/issues/188</a><br/>
Wendy Reid: #188: Sortable metadata strings propose closing topic:manifest topic:metadata<br/>
… Reopen if comes up again<br/>
… close!<br/>
Luc Audrain: +1<br/>
</details>
