### ISSUE TITLE
linking to multiple manifests

### ISSUE THREAD

**Issue by dauwhe** [w3c/wpub#189]
In our section on [linking to manifests](https://w3c.github.io/wpub/#wp-linking), we say that a resource might link to several manifests. 

> When a resource links to multiple manifests, a user agent MAY choose to present one or more alternatives to the end user, or choose a single alternative on its own. The user agent MAY choose to present any manifest based upon information that it possesses, even one that is not explicitly listed as a parent (e.g., based upon information it calculates or acquires out of band). In the absence of a preference by user agent implementers, selection of the first manifest listed is suggested as a default.

In our [steps to obtain a manifest](https://w3c.github.io/wpub/#obtaining-manifest), we say that we always use the first manifest link. 

> From the Document of the top-level browsing context, let origin be the Document's origin, and manifest link be the first link element in tree order whose rel attribute contains the token publication.

Is this a problem?

**Comment by iherman** [comment]
> Is this a problem?

It is:-) Part of the draft defines a unique choice for the manifest, whereas the general text leaves it to the UA which one to choose among, possibly, several.

What was the reason of allowing several manifests? I do not remember...

**Comment by HadrienGardeur** [comment]
We'll need to balance things out between two requirements:

- discovering a publication from a given resource
- a resource can be part of multiple publications

The current steps for obtaining a manifest are inherited from the WAM, which is designed to work with a single manifest.

**Comment by HadrienGardeur** [comment]
We've discussed this in the past multiple times, they were beyond "assumptions".

**Comment by deborahgu** [comment]
Well, I see we _do_ say 

> While this specification will provide implementation flexibility for user agents, there are still a number of areas that have been identified as potentially needing to be detailed. These include [...] resources that belong to more than one Web Publication.

Which I take as a tacit acknowledgement that we know it's a requirement _and_ we know we haven't specced it out yet.

**Comment by deborahgu** [comment]
And the other appears to be phrased as SHOULD right now:

>Resources SHOULD provide a link to the manifest of the Web Publication to which they belong to enable discovery.

**Comment by deborahgu** [comment]
For what it's worth, this seems like a sensible breakdown.  Not all resources should link to the manifest of the web publication to which they belong because they could belong to many, possibly including some that aren't under control of the resource's owner (eg. course packs).  But *if* a resource is a component of a canonical parent (eg. a single chapter of _Middlemarch_), *and if* the owner of the resource wants readers of the resource to know about the canonical parent (as with a chapter of a novel or an article in an issue of a periodical), *then* the resource should enable discover of the publication.

**Comment by BigBlueHat** [comment]
@deborahgu however, I think the question here is around what happens when that chapter of _Middlemarch_ MAY also reference multiple editions' manifests (or publication addresses or whatever). And, if/when it does, what happens when the UA finds that information out?

**Comment by deborahgu** [comment]
That is the key question in this issue, true, @BigBlueHat. Though it makes me think there should be a separate issue that the 'SHOULD'  in 

> Resources SHOULD provide a link to the manifest of the Web Publication to which they belong to enable discovery

Definitely needs to become a MAY.

**Comment by TzviyaSiegman** [comment]
I was recently reminded of the specific definition of SHOULD:

> This word, or the adjective "RECOMMENDED", mean that there may exist valid reasons in particular circumstances to ignore a particular item, but the full implications must be understood and carefully weighed before choosing a different course.

See https://tools.ietf.org/html/rfc2119. 

If this remains a SHOULD, we need to explain the exceptions to the rule.

**Comment by mattgarrish** [comment]
I'd just note that our desire for multiple manifest links and WAM's exclusion of all manifests in preference to the first one found (regardless of whether it actually points to a manifest) was noted here last fall: https://github.com/w3c/wpub/wiki/Options-for-Processing-a-Manifest

> If this remains a SHOULD, we need to explain the exceptions to the rule.

I'd recommend not taking this approach. The "should" needs to be clear what it facilitates. The reasons anyone would ignore the recommendation are too varied to try and pin down. In this case, the statement says you should provide the link for discovery. If that's not important to you, or possible, for whatever reason, you already know what you're giving up.

**Comment by mattgarrish** [comment]
And for the record, I have no issue with a "may" here. We require a link from the entry page, which generally makes the "should" here unnecessary. It probably should have been bumped down another notch when we made that decision, as I recall at one time this was a "must".

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2019/2019-03-18-pwg#section2-6).

- No actions or resolutions
<details><summary><i class="differentiate">View the transcript</i></summary>
linking to multiple manifests<br/>
Wendy Reid: #189: linking to multiple manifests<br/>
Wendy Reid: <a href="https://github.com/w3c/wpub/issues/189">https://github.com/w3c/wpub/issues/189</a><br/>
Wendy Reid: wording change to MAY (for linkage to manifests), from SHOULD.<br/>
… close?<br/>
… crickets<br/>
Ivan Herman: lukewarm discussion. Almost a year old.<br/>
Wendy Reid: close.<br/>
</details>
