### ISSUE TITLE
"resources that belong to more than one Web Publication"

### ISSUE THREAD

**Issue by deborahgu** [w3c/wpub#190]
Right now the draft says:

> While this specification will provide implementation flexibility for user agents, there are still a number of areas that have been identified as potentially needing to be detailed. These include:
> 
>     initialization expectations for a Web Publication:
>         automatic initiation v. user prompts;
>         linked v. directly loaded manifests;
>         resources that belong to more than one Web Publication.

Technical details can be worked out later, but the idea that resources can belong to more than one WP is not currently listed as a requirement.  It needs to be.

**Comment by deborahgu** [comment]
Proposed change of 5.1, which currently only defines constraints on WP, not on "resource".  Currently the text is 

> 
> A Web Publication MUST include at least one HTML document [html] that links to the manifest.
> 
> There are no restrictions on a Web Publication beyond this requirement. The Web Publication MAY include references to resources of any media type, both in the default reading order and as dependencies of other resources.

I propose:

> A resource is a file of any media type that is a component of a Web Publication, either by internal dependencies from other resources, by inclusion from the manifest, or by ???. 
>
> A resource MAY be a component of more than one Web Publication.
>
>A Web Publication MUST include at least one resource that is an HTML document [html] that links to the manifest.
> 
> There are no restrictions on a Web Publication beyond this requirement. The Web Publication MAY include references to resources of any media type, both in the default reading order and as dependencies of other resources.

Obviously this wording might change based on the result of #189. 

(I'm not clear on the complete definition we're using for "resource" -- which is part of the problem with 5.1.  It should be specific here. Eg. Would "resource" include: A file referenced in the manifest which is undiscoverable via the WP? An HTML file which references the the manifest but is unused and undiscoverable via the WP? Etc.)

**Comment by mattgarrish** [comment]
A resource is essentially the equivalent of Web Content in the linked publishing and linking document: https://www.w3.org/TR/publishing-linking/#dfn-web-content

Noting the equivalence might be simpler than trying to craft a new definition.

> A resource MAY be a component of more than one Web Publication.

This is technically true of every resource hosted on the Web, rights issues aside. We can limit a resource to one publication link by restricting the user agent processing, but we can't actually prevent a resource from appearing in more than one manifest's resource list. If we try to limit resources to one web publication, then we might need to get into the weeds here and describe what a user agent is supposed to do when it finds the same resource already assigned to a web publication, but otherwise I'd leave this as a unwritten rule of the web.

> A file referenced in the manifest which is undiscoverable via the WP

Did you mean undiscoverable by the user agent here? The manifest is defining the WP. Assuming user agent, any resource may not be available at any given point in time. The user agent has to continue to treat the reference as a resource of the publication as it could return at any time. 

> An HTML file which references the the manifest but is unused and undiscoverable via the WP

We covered this scenario in the resource list:

> If a user agent encounters a resource that it cannot locate in the resource list, it MUST treat the resource as external to the Web Publication (e.g., it might alert the user before loading, open the resource in a new window, or unload the current Web Publication and resume normal Web browsing).

**Comment by deborahgu** [comment]
> > A resource MAY be a component of more than one Web Publication.
> 
> This is technically true of every resource hosted on the Web, rights issues aside. 

I agree with the technical truth of this, but in another ticket, @BigBlueHat pointed out that we hadn't explicitly stated this as a requirement. And people coming from an epub background won't take it as a given, since it's not true in the packaged world of epub.  Is it harmful to make this explicit?

**Comment by mattgarrish** [comment]
> Is it harmful to make this explicit?

Harmful, no, but I've noticed a pattern of our having statements like this get questioned for value. If something is true regardless of our saying anything, does it need to be normatively stated?

If it does present confusion, it might make sense to make this a qualifier in the next section about linking. For example: "Only the resource list authoritatively defines whether a resource belongs to a Web Publication. Resources can belong to one or more Web Publication regardless of whether they contain any explicit links."

We probably only need to get into normative language if we do things that are counter to the open linking nature of the web, like try to actively prevent resources from being shared (e.g., scopes and the like).

**Comment by deborahgu** [comment]
I don't mind not stating it normatively. I do think he needs to be explicitly stated, though.

> If it does present confusion, it might make sense to make this a qualifier in the next section about linking. 

That makes sense. I am happy with "Resources can belong to one or more Web Publication regardless of whether they contain any explicit links."
