### ISSUE TITLE
Informing the user that the current resource is part of a web publication

### ISSUE THREAD

**Issue by dauwhe** [w3c/wpub#201]
Section 7.1 of the spec [says](https://w3c.github.io/wpub/#aff-publication-mode),

>When a user agent obtains a manifest it SHOULD display an affordance for switching the display to publication mode.

>This affordance has the following requirements:

> 1. it MUST inform the user that the current resource is part of a Web Publication

We do not require that the resource that contains the link to the manifest be part of the web publication. In this situation, what is the obligation of the affordance? And is there an obligation to continue to indicate that the "current resource" is a part of the web publication as the user navigates between such resources while in publication mode?

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2019/2019-03-18-pwg#section2-8).

- No actions or resolutions
<details><summary><i class="differentiate">View the transcript</i></summary>
Informing the user that the current resource is part of a web publication<br/>
Wendy Reid: <a href="https://github.com/w3c/wpub/issues/201">https://github.com/w3c/wpub/issues/201</a><br/>
Wendy Reid: #201: Informing the user that the current resource is part of a web publication<br/>
Ivan Herman: should move to affordances, not in spec anymore.<br/>
Wendy Reid: close as no longer relevant.<br/>
</details>
