### ISSUE TITLE
Document should call out specific actions/notes for User Agents

### ISSUE THREAD

**Issue by lrosenthol** [w3c/wpub#204]
Although the topic came up in the discussion of infoset, it applies across the entire document.

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2019/2019-03-18-pwg#section2-9).

- No actions or resolutions
<details><summary><i class="differentiate">View the transcript</i></summary>
Document should call out specific actions/notes for User Agents<br/>
Wendy Reid: <a href="https://github.com/w3c/wpub/issues/204">https://github.com/w3c/wpub/issues/204</a><br/>
Wendy Reid: #204: Document should call out specific actions/notes for User Agents<br/>
Ivan Herman: Affordances too.<br/>
Wendy Reid: close<br/>
</details>
