### ISSUE TITLE
Hints about resources in "default reading order" or "list of resources"

### ISSUE THREAD

**Issue by HadrienGardeur** [w3c/wpub#222]
This is based on my gap analysis between EPUB 3.2 and WP: https://github.com/w3c/wpub/issues/176#issuecomment-382634697

In EPUB, it's possible to provide hints about what's included in a resource using `properties` in the `spine`.

While some of these properties feel like rel values (`cover-image`, `nav`), the rest of them are purely meant to indicate what's contained in the linked resource (`mathml`, `scripted`, `svg`, `remote-resources`).

Do we need these hints at all in WP or EPUB4?

**Comment by danielweck** [comment]
I would be interested to know if any EPUB reading system implementation use this per-document "metadata" to derive specific behaviours. For example, it is my understanding that Readium checks for actual occurrences of MathML markup in HTML documents in order to trigger the injection of MathJax (a JavaScript rendering library for mathematical formulas). Just curious :)

**Comment by TzviyaSiegman** [comment]
+1 to @danielweck 

I think the equivalents or near equivalents to `rel` values are valuable. These indicate a specific, possibly unique item in the WP. Does a UA need to know every instance of scripting or math in a WP?

**Comment by HadrienGardeur** [comment]
@TzviyaSiegman I think that there's a case specifically for MathML since it's not well supported in browsers. 

This could be a useful hint that a UA needs to provide a polyfill.

**Comment by GarthConboy** [comment]
We don't find these hints all that trustworthy in EPUB today.  So, I'd somewhat lean toward "punt."

**Comment by BigBlueHat** [comment]
> This could be a useful hint that a UA needs to provide a polyfill.

Don't developers provide polyfills to UAs? A "polyfill" provided by a UA would be a feature, wouldn't it?

**Comment by rakutenjeff** [comment]
We need this to only "polyfill" when necessary.

**Comment by rakutenjeff** [comment]
From reading system point of view, information such as mathml per item is very helpful as it's indicator of something meaningful (no matter it's trustful or not. Creator could put "cover-image" to wrong item as well).

**Comment by HadrienGardeur** [comment]
Readium is also using the MathML hint to trigger the injection of a polyfill in a resource.

**Comment by TzviyaSiegman** [comment]
I think most UA developers commented that the attributes in EPUB are not valuable, so we should not continue using them. I propose closing this issue.

**Comment by HadrienGardeur** [comment]
There's one exception: MathML. 

This is used in Readium and (correct me if I'm wrong @rakutenjeff) by Kobo at least.

**Comment by dauwhe** [comment]
This seems like an example of putting a burden on authors for the convenience of developers. If I'm putting equations (or for that matter, any other content) on the web, it is my responsibility to make sure that content is available to my target audience, and there are many ways I can accomplish that goal.

**Comment by HadrienGardeur** [comment]
In this case @dauwhe, you can't expect UAs to support MathML on your behalf.

This means that it's also your responsability to embed a polyfill for MathML.

**Comment by llemeurfr** [comment]
From a discussion we just have in the Readium community it appears that Web Readers are in good position to check the html content before injecting mathjax js; whilst native apps, because of their architecture, prefer having a flag even if it's not 100% reliable, for efficiency reasons. I'll talk to @danielweck about this.

**Comment by JayPanoz** [comment]
> Don't developers provide polyfills to UAs? A "polyfill" provided by a UA would be a feature, wouldn't it?

In theory yes. 

In EPUB practice, a lot of authors expect UA to be a proxy polyfilling everything for them because they absolutely don’t want to handle anything JS – i.e. in some cases, the UA is using the same polyfill the author could have used herself/himself.

**Comment by rakutenjeff** [comment]
Ok, so as a creator I wanted to create a content that some chapter has two versions. One (A) has mathml and the other (B) use image or inject MathJax just in case UA/RS does not support mathml. And I want RS/UA to default use (A) if can support MathML and fallback to (B) if can not support MathML.

In this case would hint for mathml be necessary for creator?

**Comment by TzviyaSiegman** [comment]
**What problem are you trying to solve?**
There is no problem, just a difference between EPUB and WP

**What solution are you proposing?** 
Including properties in infoset that hint about inclusion of items such as MathML

**Why do you believe this is the ideal solution?**
Unclear that anyone does

**What alternatives did you consider**
Allowing UAs to check content (to inject polyfills, etc) instead of relying on hints that are not always reliable.

Proposal: no hints in infoset

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2019/2019-03-18-pwg#section2-11).

- No actions or resolutions
<details><summary><i class="differentiate">View the transcript</i></summary>
Hints about resources in “default reading order” or “list of resources”<br/>
Wendy Reid: <a href="https://github.com/w3c/wpub/issues/222">https://github.com/w3c/wpub/issues/222</a><br/>
Wendy Reid: #222: Hints about resources in “default reading order” or “list of resources”<br/>
… those EPUB hints about linked resources (SVG, scripting)<br/>
Ivan Herman: which are values<br/>
Wendy Reid: UA’s can check content if need be.<br/>
Wendy Reid: garth: We don’t find the hints particularly trustworthy, EPUB wasn’t successful with this one<br/>
Garth Conboy: not really trustable, should close<br/>
Luc Audrain: burdens on author<br/>
Wendy Reid: close!<br/>
</details>
