### ISSUE TITLE
Can a table of contents refer to resources outside the default reading order?

### ISSUE THREAD

**Issue by mattgarrish** [w3c/wpub#276]

**Comment by avneeshsingh** [comment]
Yes TOC should point to resources that are not in default reading order. It is possible that default reading order has just one resource, and most of the resources in publication are non-linear. TOC would need to provide Navigation to such resources.

And +1 to 2nd part also. If the WP is offline or packaged then TOC may not be able to lead to external resources.

**Comment by HadrienGardeur** [comment]
I would allow both.

An external resource is simply a resource that is not referenced in `readingOrder` or `resources`. On the Web it makes no sense to have additional restrictions in the TOC for such resources.

**Comment by iherman** [comment]
@mattgarrish I may have a study on some public but onerous document; let us say I may have a study on-line on the French constitution. The study itself is my WP, I can have a TOC with pointers to various chapters of that study and, on the Web, I believe it is a perfectly fine step to add a reference, in the Appendix, to the constitution text itself using a public URL. Ie, the constitution _itself_ is not part of the publication, but for the reader _on the Web_ it gives a natural link.

I understand the example is a bit contrived and can be disputed. It may not be good authoring practice either. But _forbidding it_ may be a step too far...

**Comment by llemeurfr** [comment]
@iherman isn't the good authoring practice (in scholarly publishing) to include in the ToC a link to an Appendix page (inside the publication) and express external links in the Appendix (as bibliographic links)?

**Comment by HadrienGardeur** [comment]
Good authoring practice is something quite different from disallowing such use case.

**Comment by mattgarrish** [comment]
What you're suggesting is a use case doesn't sound at all like a use case for a table of contents, though.

I don't disagree with you that having a navigation aid to external resources would be useful, but it has nothing to do with the locating yourself in the structure of the publication.

**Comment by llemeurfr** [comment]
If we say ok to external links in the ToC, let's discuss what the risk is when the publication is offlined. IMO this is not really a technical risk, as all "404" will need to be trapped.

It's more a UX issue, as a modal box will appear in front of the user, saying something like "This resource can't be accessed offline, join the Web if you want to access it." The user will meet such messages during his navigation in the publication: do we accept that he can face it in the ToC also?

Personally I have nothing strongly against ... As a user I would nevertheless shout at the bloody author who did this to me.

**Comment by iherman** [comment]
@llemeurfr you are absolutely right that some sort of a decent UI will be needed by (decent) implementations to produce a clearer 404 response. But that is not related to the TOC; if an article has a reference to a large video that is not offlined, the same issue arises. I do not see the TOC as being fundamentally different.

**Comment by laudrain** [comment]
Good and usual authoring practices put external references in an appendix of some sort.
I don't support the idea of TOC entries pointing directly to these external documents.
After all, TOC means Table Of **Content**.

**Comment by rakutenjeff** [comment]
TOC _SHOULD_ ONLY refer to resource that appears in reading order.
Allow TOC refer to content that out of reading order might get problem in some edge case since reading system will not know where to go once user at end of out-of-reading-order item. RS might misleading user that this book is finished since it's not inside of any item of reading order. If user knows that he/she is in the middle of nowhere of of this WP and there is a wrong dead end ahead and can just press the back button on UA then it's fine but I doubt user could notice that.

**Comment by BigBlueHat** [comment]
Presumably a Table of Contents is (and always has been) a table of the contents of a publication. Not sure it needs redefinition.

**Comment by avneeshsingh** [comment]
It looks that discussion has expanded from including external links in TOC to TOC pointing to only reading order.
* Regarding TOC pointing to only reading order: It is very much possible that the publication has important content which does not lie in the reading order for example a publication that decides the story on the basis of a decision tree.
* Regarding TOC pointing to external link: I always emphasize predictability as an important feature for people with disabilities. Placing of external links in TOC goes against this.

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2018/2018-09-10-pwg).

- `RESOLVED:  the entries in the DOC-TOC table of contents SHOULD point into the bounds of the publication`
<details><summary><i class="differentiate">View the transcript</i></summary>
Garth Conboy: The DOC-TOC element - if it can point to resources outside of the default reading order. I will throw out a prejudice that the thing - and Dave is going to come in saying ‘it’s not webby’ - my initial 2 cents is that the TOC should point to items in the resources or reading order.<br/>
Garth Conboy: The title of the issue is: “outside the reading order” and additional resources. If it’s a publication, then the TOC should point into the publication as it’s defined by the boundary.<br/>
Jeff Buehler: I found that over the years the TOC isn’t always reliable, such as resources not available within. The solution is to create another XML file…<br/>
Garth Conboy: I don’t think we want the TOC to have more power, but the pointers in the DOC-TOC, whether the links in there can point only to the items within the publication.<br/>
Garth Conboy: it wouldn’t pull all of that section’s links into the TOC (the external links)<br/>
Ivan Herman: Any scholarly publication’s structure, yes there’s a section of references, but the TOC includes a reference to the section, but not the external links.<br/>
Dave Cramer: This is more a discussion of scope and boundaries than what happens if a link in a TOC goes somewhere beyond ‘inside the publication’ That is a larger question we haven’t really addressed. What I have an external link elsewhere. What happens, how do we show to the user that they have left the web publication.<br/>
Garth Conboy: Certainly in web publication land, Nick’s suggestion of additional reading - we do agree that the default reading order + additional resources is the bounds of the publication, so - do we - for the TOC should it only fit within the bounds of the publication. We can’t prevent content creators from putting a link to whatever - but we need the rule if it is ignored or not.<br/>
Joshua Pyle: I tend to agree, and prefer for the TOC to be within the bounds of the publication. What we’re doing with web publications is creating the ability to bind different things together. We could mix-and-match pages, but the point of the WP is to bind them together.<br/>
… The TOC should direct you within the bounds of what you’ve just created. Things like references, they’re all external links. They should be separate from the TOC. It would be frustrating for a user to click and link and leave the document.<br/>
Juan Corona: nice explanation josh +1<br/>
Garth Conboy: We’re defining a bounded collection of resources, so the TOC should point within those bounds.<br/>
George Kerscher: I’m envisioning reading order in the additional documents to have link relationships to other documents within the publication, whereas when you get outside the publication there is no relationship. I’m in agreement that the TOC defined as such helps solidify this.<br/>
Ric Wright: I totally agree with what Josh said - well put. The other comment, more of a question, more relevant here. Isn’t this related to the conversation in Chicago about would we allow resources to be external to the document? As a RS developer, that makes me nervous as it’s a security concern.<br/>
Garth Conboy: I agree, moving within the TOC you’re moving within the publication.<br/>
Evan Owens: within journal publishing, you have links to where the article was published, so you would be linking out to a different document/page<br/>
Garth Conboy: You’re envisioning a page that is a pointer to other publications, but it would be a TOC?<br/>
Joshua Pyle: I come from the journal publishing world, and yes, an article would be a web publication. The issue for that article would be a web publication of web publications. In which case, the Table of Contents is - you’re still within the bounds of the issue, we’re still binding that. It could be a compilation - all of that stuff… it doesn’t matter where it lives, as long as the manifest defines it as part of the publication.<br/>
… We have to drop the notion of domain - it’s still a single web publication and the TOC is within it.<br/>
Ivan Herman: Slightly different question from George if someone wants to respond.<br/>
Garth Conboy: I thought it was well summarized as nested web publications, so the parents can point to it’s children, which are part of the boundaries.<br/>
Joshua Pyle: An out-of-bounds error :-)<br/>
Ivan Herman: Let’s say we decided that a reference in a TOC should be within the bounds. The question is, what happens if someone makes a mistake. What is the reaction? It’s a bit like we already have requirements for a person but if a structure doesn’t have a name, the structure is invalid and taking out of the list.<br/>
… Let’s say we have a process that creates a machine readable TOC, and the algorithm realizes that one of the references is out of the doc, what should it do?<br/>
Garth Conboy: We clearly have to deal with that, and it comes down to if it becomes a should or a must, and what happens if you violate<br/>
Matt Garrish: Probably a must-not is a bit strong, we won’t stop people. It should be a recommendation for the reasons already laid out, it will be confusing to the user and leave it at that. We’re not going to force people, and reading systems are going to have to handle this. Throwing it out is going to be odd, but when it’s extracted from the reading system, it’s not a place we should go, we should just recommend not doing it.<br/>
Joshua Pyle: +1 to SHOULD<br/>
Garth Conboy: maybe this does inherently answer Ivan’s question, that we can resolve this issue, at least for the moment, that the entries in the DOC-TOC table of contents should points into the bounds of the publication<br/>
Proposed resolution: the entries in the DOC-TOC table of contents SHOULD point into the bounds of the publication (Ivan Herman)<br/>
Avneesh Singh: +1<br/>
Garth Conboy: +1<br/>
Derek Jackson: +1<br/>
Zheng Xu: +1<br/>
Charles LaPierre: +1<br/>
Juan Corona: +1<br/>
Joshua Pyle: +1<br/>
Jeff Buehler: +1 also should, 0 to must<br/>
Caitlin Gebhard: +1<br/>
Ivan Herman: +1<br/>
Franco Alvarado: +1<br/>
Garth Conboy: If that is consensus, that is probably suitable for us to get in there and resolve the issue.<br/>
Dave Cramer: +1 to should, -1 to must<br/>
Ric Wright: +1<br/>
Ben Schroeter: +1<br/>
Marisa DeMeglio: +1 should<br/>
George Kerscher: +1<br/>
Joshua Pyle: As we are specification writers, the best we can do is should, must, and must not, but it’s up to implementors to determine what should happen when they come across a should/must/must-not, etc.<br/>
Garth Conboy: It’s more incumbent on us to determine what should happen with must and must not….<br/>
Ivan Herman: At some point in time we will have to look at this for the document. If there is a should or should-not, then there is a checker that should raise a warning (the difference between an error or warning) so a future epub checker could raise a warning.<br/>
Dave Cramer: I think we need to make distinction between HTML and the manifest. We control the manifest, but not HTML. We should not be making any restrictions on HTML<br/>
Resolution #2: the entries in the DOC-TOC table of contents SHOULD point into the bounds of the publication<br/>
</details>
