### ISSUE TITLE
What does it mean for a resource to be listed as a link?

### ISSUE THREAD

**Issue by dauwhe** [w3c/wpub#289]
I've been trying to look at the spec from the point of view of an author unfamiliar with our work, who would like to create a web publication. One thing that seemed particularly confusing was the concept of [links](https://w3c.github.io/wpub/#links). 

> The links property enumerates resources that are significant to a Web Publication but are not essential to the processing and rendering of it

So much of the language in this section is ambivalent. "Could", "might", "might affect the usability of the Web Publication in certain scenarios", and the usual "shoulds". But what does it mean for a resource to be included in this list? Will they be packaged, or not? Will they be available offline, or not? If a user navigates to such a resource, would they have the same UI as in the rest of the publication? We say elsewhere that such resources are **not** part of the publication. 

As an author, I need to know what are the consequences are of including a resource in this list, and what the consequences are of omitting it. The spec does not help me make that decision.

**Comment by HadrienGardeur** [comment]
`links` is primarily meant to discover resources that are not part of the resource but could still be useful:

- an external metadata record
- an OpenSearch Description Document that provides server-side search over the entire publication
- an alternate version of a publication in a different format
- an annotation service

I don't think that there are strong consequences in omitting a resource from `links` but you might get additional affordances from a UA when you do include them.
There are no expectations for these resources to be offlined or packaged, quite the opposite.

**Comment by TzviyaSiegman** [comment]
> As an author, I need to know what are the consequences are of including a resource in this list, and what the consequences are of omitting it. The spec does not help me make that decision.

I believe @dauwhe is saying that the intention of the spec is not clear enough. Not everyone reading the spec will be able to contact @HadrienGardeur for advice. This means that we have some editing to do.

**Comment by dauwhe** [comment]
> There are no expectations for these resources to be offlined or packaged, quite the opposite.

Should we say these resources must not be offlined or packaged? At least that would provide some clarity for authors.

**Comment by BigBlueHat** [comment]
All four of these scenarios have defined link relationships which are *currently used* for discovery, processing, etc.

> an external metadata record
[rel="describedby"](https://www.w3.org/TR/powder-dr/#appD)
> an OpenSearch Description Document that provides server-side search over the entire publication
[rel="search"](https://github.com/dewitt/opensearch/blob/master/opensearch-1-1-draft-6.md#autodiscovery) (used on this page, in fact)
> an alternate version of a publication in a different format
[rel="alternate"](https://tools.ietf.org/html/rfc4287#section-4.2.7.2) (also in use here)
> an annotation service
[rel="http://www.w3.org/ns/oa#annotationService"](https://www.w3.org/TR/annotation-protocol/#discovery-of-annotation-containers)

Given that a publication address MUST return and HTML page, the expectation of authors (it would seem) would be to express (as they do now) these relationships from that resource in order to trigger the expected discoveries.

Repeating them inside the JSON doesn't seem to add any value to the browser/consumers currently looking for these types of relationships.

**Comment by dauwhe** [comment]
> an OpenSearch Description Document that provides server-side search over the entire publication

How might this work? A content author has to create some sort of search functionality, document it, but then hand off implementation to some unspecified WP-aware user agent that has no obligation to provide such functionality?

The web is pretty clear on who is responsible for providing any sort of affordance: it's the content author. EPUB is pretty clear on who is responsible for providing any sort of affordance: it's the reading system. WPUB seems to be in the middle, where it's completely unclear who is responsible for anything.

**Comment by iherman** [comment]
Yes, the description is vague. I know that @mattgarrish had some fight with himself coming up with a good text, but clearly there are improvements to do.

I think the statement of @dauwhe whereby "these resources must not be offlined or packaged?" works for me, although I would probably use "should" instead of "must".

B.t.w., not all the examples can be handled by HTML `link`+`rel`. In this sense, I am actually not sure the opensearch service is a good example indeed, and I would think that this should be used via a `link`+`rel` as on the current Web and leave it to the UA. My examples are rather resources that _are_ used to render, but where we do not expect offlining due to practical issues like size, or legal, like copyright. References to a large video, font files, large scientific datasets, etc., come to my mind.

**Comment by iherman** [comment]
B.t.w., the fact that certain links can be set as HTML `<link>`+`rel` is not a panacea either. It of course gives a good feeling of using what HTML defines, but the sad reality is that most (all?) browsers ignore those links which are considered as some sort of metadata left to special applications. There are only some exceptions like `stylesheet` or, these days, `manifest`. The best (or worst? saddest?) example is the fact that browsers seem to ignore `rel=next` or `rel=previous` in spite of the fact that these values are almost as old as HTML itself:-(

Put it another way: whether the author puts these types of values (e.g., a reference to an ONIX data) into a `<link>` in HTML or in the manifest does not really mean any difference: non-WP aware browsers will ignore the link despite the `rel=describedby`, and it would need a WP aware engine to do anything with them. Actually, using the manifest version has the advantage of giving the possibility of adding a title _and_ a more verbose description, if it makes sense.

That said, I would have no problem of relying on HTML `<link>` elements for all those cases when we do have a documented evidence that they are used by non-WP aware browsers for anything useful. I would still consider that as a fall-back to the manifest version, and I would still say that the WebIDL defined interface should include those as well, ie, a processor should pick them up from the primary entry page and put into the same data. Just as we do with the `<title>` element.

**Comment by mattgarrish** [comment]
> I think the statement of @dauwhe whereby "these resources must not be offlined or packaged?" works for me, although I would probably use "should" instead of "must".

The problem I found is there's no common thread that makes this a necessary restriction. Sometimes you don't want to package or take linked resources offline (third party scripts), but why would you tell a user agent that can use a font or metadata record that it shouldn't take it offline?

There's probably a case for not packaging them, though, since that would leave it to other user agents to determine for themselves if they want to grab and store the resource.

**Comment by iherman** [comment]
closing by virtue of #301
