### ISSUE TITLE
Duration of an audiobook

### ISSUE THREAD

**Issue by HadrienGardeur** [w3c/wpub#307]
For an audiobook, we need to ideally express:

- the total duration of the publication
- the duration of individual audio resources

Schema.org uses https://schema.org/duration for this purpose but there are a few points worth listing:

- ISO 8601 for a duration is not always the friendliest format
- media fragments ([used in a TOC for example](https://github.com/w3c/wpub/blob/master/experiments/audiobook/toc.html)) are based on seconds instead
- it would require the use of `"@type": "Audiobook"` as well, since `duration` is not defined on `CreativeWork` or `Book`
- it's also undefined right now on `PublicationLink` or the equivalent in schema.org that's currently a draft (I can't remember the exact term)

For the duration of individual resources listed in the reading order, the same issue raised in https://github.com/w3c/wpub/issues/229#issuecomment-413520551 applies as well.

**Comment by danielweck** [comment]
Thanks for pointing this out.

Indeed, I am discovering the "duration" ISO_8601 syntax:
https://en.wikipedia.org/wiki/ISO_8601#Durations

I am more familiar with Media Fragments:
https://www.w3.org/TR/media-frags/#naming-time

...and of course SMIL (well, the EPUB3 Media Overlays simplified model):
http://www.idpf.org/epub/31/spec/epub-mediaoverlays.html#app-clock-examples
https://www.w3.org/TR/SMIL3/smil-timing.html#Timing-ClockValueSyntax

**Comment by llemeurfr** [comment]
You're right @HadrienGardeur, the ISO 8601 syntax for a duration is un-intuitive (but easy when you look closely) and I didn't see it used in the read world (e.g. real life XML schemas). 

We must consider that this duration property is essentially used for display purposes (in the UA), therefore the second is a sufficient precision and an audiobook duration will never be much more than 24 hours. A duration is minutes or seconds would therefore be ok.

I'm sligthly in favor of reusing the SMIL timecount syntax (e.g. `45min`, or `30s`). Easy to write, to read and to parse. I understand this is a fork from schema.org. Nb: using the ISO 8601 syntax we would have values like `T45M` or `T30S`.

Apart from the global duration of the audiobook (which will appear along with the description of the work), my feeling is that the duration of individual "chapters" should be expressed at the level of the ToC rather than the level of individual (physical) resources.

**Comment by iherman** [comment]
Is ISO 8601 very different from the [xsd datatype for duration](https://www.w3.org/TR/xmlschema11-2/#duration)? The advantage of xsd is that it is integral part of the environment...

**Comment by llemeurfr** [comment]
@iherman no it's the same. Did you see xsd:duration used in well know XML schemas?

**Comment by iherman** [comment]
I have not really, but simply because I never really looked for it, ie, my opinion is not really relevant...:-(

**Comment by iherman** [comment]
All that being said, I am a little bit wary of using something different than schema. That would mean that we would have to use a different property than https://schema.org/duration, ie, that type of data in our metadata will not be necessarily recognized...

(But I do not have experience in this, ie, I do not have a strong opinion on this.)

**Comment by HadrienGardeur** [comment]
> Apart from the global duration of the audiobook (which will appear along with the description of the work), my feeling is that the duration of individual "chapters" should be expressed at the level of the ToC rather than the level of individual (physical) resources.

I think these are two different things. 

At a ToC level, we can point to a range using media fragments, but IMO that's mostly useful for a "timeline" feature or displaying the relevant title when listening to an audiobook.

**Comment by llemeurfr** [comment]
> At a ToC level, we can point to a range using media fragments, but IMO that's mostly useful for a "timeline" feature or displaying the relevant title when listening to an audiobook.

If we stay at a functional level, we should indicate at the Toc level a duration that the user can easily understand (after some processing for proper display), so that he can choose if he has enough time to listen to the chapter. It's an indication of "volume". I agree that such information should also be usable in a timeline. If the ToC is expressed in HTML as it is today, this can be inserted using microdata (again). Does a media fragment makes the trick in this case? I doubt.

**Comment by llemeurfr** [comment]
> I think these are two different things.

Maybe. What is the interest of a duration at the (physical) resource level? there is no benefit for the user IMO. There may be a benefit for the UA: which one?

What is sure is that the duration of the whole audiobook (good for the user) and the duration of individual resources are not on the same plan.

**Comment by HadrienGardeur** [comment]
> Maybe. What is the interest of a duration at the (physical) resource level? there is no benefit for the user IMO. There may be a benefit for the UA: which one?

- All audiobooks have tracks, very few have ToC right now, this is an easy way to build a timeline based on tracks
- This can also help with caching (the UA would for example cache an hour worth of additional audio)

That second point is something that we really need to explore by the way. Without indications such as:

- duration (audio/video)
- size (images, audio and video)
- resolution (images and audio)
- bitrate (audio and video)

... it'll be very difficult for a UA when it should or shouldn't cache something for offline reading or download it in a package.

The size of the cache will always be limited by:

- the available storage of a given device
- the storage available specifically to the UA
- various limits that are set for specific APIs (that's the case for the Cache API used by Service Workers for instance)

**Comment by HadrienGardeur** [comment]
>If we stay at a functional level, we should indicate at the Toc level a duration that the user can easily understand (after some processing for proper display), so that he can choose if he has enough time to listen to the chapter. It's an indication of "volume". I agree that such information should also be usable in a timeline. If the ToC is expressed in HTML as it is today, this can be inserted using microdata (again). Does a media fragment makes the trick in this case? I doubt.

That's not what I'm suggesting at all, I don't want to see microdata in the ToC (or anywhere frankly).

[Here's an example of an audiobook Toc](https://w3c.github.io/wpub/experiments/audiobook/toc.html):

- as you can see, fragments are expressed using `#t=`
- but it's also possible to provide a range ([called a time interval in the spec](https://www.w3.org/TR/media-frags/#naming-time)) using such media fragments such as `#t=10,20`

**Comment by llemeurfr** [comment]
**About media characteristics**

>  without ... it'll be very difficult for a UA when it should or shouldn't cache something for offline reading or download it in a package.
Apart from the size of the resource, why are the characteristics you are listing useful for caching?

> resolution (images and audio)
The common meaning of resolution is  "the recommended printing resolution for an image in dots per inch" -> raster images only, e.g 72 dpi. 

IMO media characteristics are useful when one needs 1/ to check that the UA can read the content (this is the case for the audio codec value) 2/ to select one piece of content among several alternatives. 
 
Such checking or selection is usually  made on:

audio
- codec or format (the distinction can be difficult; AAC is a codec, WMA is a format, MP3 is a codec and a format). 
- channels (1, 2 or more)
- bitrate (in kbits per second)
- sample size or linear bit depth (number of bits per audio sample)
- sample rate (number of audio samples per second, expressed as a sampling frequency in KHz)

video
- codec or format
-  aspect ratio (e.g. 16:9, 4:3)
- (average) bitrate (in kbits per second)
- frame rate (number of video frames per second, i.e. the rate at which the material should be shown in order to achieve the intended visual effect)
 
Questions are:
- isn't the codec/format type sufficient for checking that the UA can read the content? 
- should we create a structure which allows alternative renditions of media content?

If the answers are yes to the first and no to the second, I don't see why these characteristics are interesting in our format. 

**About the duration of a section in an audiobook ToC**

Which a simple time, the UA cannot easily infer the duration of the section. With a time interval it is possible with some processing.

Question is: 
- do we want to impose a time interval here?
- or do we say that the UA may or may not be able to show the duration of a section, depending the way the author understands some note in the best practices document?
- or do we accept to consider microdata as an OWP technology?

**Comment by HadrienGardeur** [comment]
> Apart from the size of the resource, why are the characteristics you are listing useful for caching? IMO media characteristics are only useful when one needs 1/ to check that the UA can read the content (this is the case for the audio codec value) 2/ to select one piece of content among several alternatives.

This is different from what I've pointed out in https://github.com/w3c/wpub/issues/307#issuecomment-413821054.

Even if you support the format, you might not want to attempt caching a 400Mb video when your overall available cache is 50Mb (I think that's the total cache available in Safari for example).

> With a simple time, the UA cannot easily infer the duration of the section. With a time interval it is possible with some processing.

That's not entirely true. Take a look at the [Flatland example](https://github.com/w3c/wpub/blob/master/experiments/audiobook/toc.html) and you'll see that it's very easy to extract a timeline from it.

> do we want to impose a time interval here?

IMO that's not necessary.

**Comment by danielweck** [comment]
I think promoting the use of time intervals instead of single time pointers for the "table of contents" links is a bad idea, because ranges clearly indicate when playback *ends*. TOC links conventionally reference *discrete* locations to navigate to, which provides a consistent user expectation whereby whenever such a link is activated, playback (i.e. the reading / listening experience) continues until the end of the audio book, unless otherwise interrupted.

This applies to "continuous" media (as per the SMIL definition), which is not just "audio books", but also text-only publications that are narrated via synthetic speech (thereby providing a flowing aural rendition), as well as synchronized text + pre-recorded audio (EPUB3 Media Overlays).

PS: by "table of contents" I really mean any navigational structure that references locations within the publication resources, such as hierarchical list of headings, flat list(s) of landmarks, page list, etc.

**Comment by HadrienGardeur** [comment]
Going back to the initial issue, these are the two questions that we want to address in our next call:

- do we need to express the duration of the whole publication?
- do we need to express the duration of individual resources?

Once we've answered both questions, we can decide how (keeping in mind that https://schema.org/duration is the most likely candidate).

**Comment by rakutenjeff** [comment]
As RS we probably need to express duration of the whole publication in for example book shelf and individual resources in "toc".

**Comment by HadrienGardeur** [comment]
> As RS we probably need to express duration of the whole publication in for example book shelf and individual resources in "toc".

In the TOC rather than in `readingOrder`? Why?

**Comment by rakutenjeff** [comment]
It is because we put chapter duration in `toc` level of RS affordance (of course data of duration could be eventually existed in `readingOrder`) and at this moment my understanding is we have not decided if RS should treat `readingOrder` as `toc` of whole book.

**Comment by HadrienGardeur** [comment]
They're two completely different things. To illustrate with the Flatland example:

- [this is the reading order](https://github.com/w3c/wpub/blob/master/experiments/audiobook/flatland.json#L20)
- [this is the TOC](https://github.com/w3c/wpub/blob/master/experiments/audiobook/toc.html#L7)

**Comment by rakutenjeff** [comment]
Ok, I was confused by the `readingOrder` include some information (`"name": "Part 1, Sections 1 - 3"`) seems needed for `toc`. Thanks for clarification.
Then we need this in `toc` rather than `readingOrder` since it would be better for UI to display duration in Table Of Content (duration for each item in `toc`) because item in `toc` could be sub items of `readingOrder`.
I don't think it's practical to calculate duration of each `toc` item from `readingOrder`.

**Comment by HadrienGardeur** [comment]
Hmm I disagree.

All audiobooks produced today have the equivalent of a `readingOrder` and it would be very easy to provide the duration of such tracks. 

It's not clear how many audiobooks have the equivalent of a TOC right now. I also don't think that a TOC will ever be a requirement in WP.

By requiring a duration in `readingOrder` and recommending media fragments in the TOC:

- we can calculate a timeline tied to the TOC when both are present (that's easy to calculate)
- and we can always fallback a list of tracks for every other case

**Comment by rakutenjeff** [comment]
> and it would be very easy to provide the duration of such tracks.
I think this is base on presumption that TOC is machine readable but we are not sure about it yet in wide WP scope.

> All audiobooks produced today have the equivalent of a readingOrder
What if some audiobook could be voice controlled by google home in near future?

> I also don't think that a TOC will ever be a requirement in WP.
Neither me.
I can not say duration is requirement as well. I would rather that spec can provide a (standard) way to express duration than make it as a requirement just like `toc`. Base on this, maybe as you said `readingOrder` is an alternative way (and better way eventually?) but think about it straightforwardly RS would need duration to be displayed corresponding with `toc` item. Is there any reason we need to put it into `readingOrder` and calculate it to `toc` rather than just put it in `toc`?

Maybe we can extend this a bit by 

1. do we need to express the duration of the whole publication?
2. do we need to express the duration of individual resources?
3. do we need to express the duration of individual toc item?

I agree with 1, thinking it would be nice if we have 3 but I wonder what 2 can provide rather than toc.

**Comment by wareid** [comment]
Summary from the taskforce meeting (for the benefit for the rest of the group):
There are two options to express duration (and many places where duration can be expressed), one is to use the schema.org schema:duration ([Duration - schema.org](https://schema.org/Duration))  which requires including the “@type” of Audiobook and the time format from ISO 8601. The other option is to include duration in the resources, which would require an extension of the publicationLink we are already using. 
The importance of how we provide information comes up in a few ways for UserAgents:
	* Total duration of the audiobook
	* Duration of chapters within the TOC 
	* Duration of files 
We’d like to discuss how best to express this in the WP in general (this also would likely apply to video in some ways as well).

**Comment by iherman** [comment]
Thanks @wareid for the summary. Just few very general remarks.

- We already explicitly mention the schema.org `Audiobook` type in the spec, as the [recipient for the `readBy` term](https://w3c.github.io/wpub/#wp-creator-manifest). Ie, using schema.org's `duration` does on introduce anything new in this respect. Extending `publicationLink` in this respect is of course under our control, ie, no problem either. I do understand that the ISO formalism is ugly (it is:-), but I would still prefer to stick to schema.org whenever we can.
- My absolutely and completely layperson's comment is whether the structures we are discussing here are valid for audiobooks only. I could imagine, for example, a 'publication' consisting of a series of videos (something like a playlist) which would share many of the issues that are discussed here. I know that generalizing is always dangerous, because one can become lost in further details, but I nevertheless wonder whether there is a more general term that does exist that we may use, although audiobooks would be the most important embodiment of that category...

**Comment by HadrienGardeur** [comment]
> My absolutely and completely layperson's comment is whether the structures we are discussing here are valid for audiobooks only. I could imagine, for example, a 'publication' consisting of a series of videos [...]

That's entirely correct and ideally we want to address this by potentially introducing the ability to specify the bitrate (audio & video) and the height/width (video and images) as well.

Since these terms are already available at schema.org (https://schema.org/bitrate, https://schema.org/height and https://schema.org/width), this would simply require extending the publication link model with them as well.

**Comment by iherman** [comment]
@HadrienGardeur 

> That's entirely correct and ideally we want to address this by potentially introducing the ability to specify the bitrate (audio & video) and the height/width (video and images) as well.

Thanks for the confirmation. Two (not necessarily high priority) comments. 

1. Is there an accepted term in the community for a publication including, e.g., videos (I note that we may touch some of the animated manga/BD type publications with this)? `audiobook` is probably the most important category and type for now in practice, but we may want to be prepared for having another publication type for the more general category. This may be an issue to take up with @danbri at TPAC: extensions of schema.org to include other forms of publications.
2. While extending the `PublicationLink` is the obvious way (and I am fine with it) to add these additional attributes, we may want to look at the clean semantics. Indeed, whilst `PublicationLink` started as some sort of a copy of a `<link>` element by adding media type and the like, adding, e.g., duration means that we are characterizing _the targeted resource itself_, and _not_ the link (knowing very well that the borderline between these two are fuzzy). This may lead to two possible changes:
    1. Rename `PublicationLink` to something like a `PublicationResource` (I know, this is only a change of name, but those are important).
    2. If we say `PublicationResource` we might want to consider the term `id` instead of `url` (or have both), because we want to have the subject clearly stated for the statements we are adding. (Yeah, my Semantic Web past is resurfacing:-(

Again, these are not central issues for now, just jotting them down for a possible later discussion. And if there is consensus that this is worthwhile discussing, I am happy spawn these into a separate issue(s).

Cc @TzviyaSiegman @GarthConboy @wareid

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2018/2018-10-01-pwg.html#section1-1).

- No actions or resolutions
<details><summary><i class="differentiate">View the transcript</i></summary>
1.1. duration, ISO format<br/>
Ivan Herman: link: Issue 307<br/>
Wendy Reid: one of the challenges is the relationship between track length and chapter length<br/>
… so how do we express duration in an audiobook?<br/>
… schema has audio duration, using an iso format (ISO 8601)<br/>
… this could also affect video content<br/>
… our alternative would be to extend publicationLink<br/>
… we also discussed bitrate and format, which would be expressed similarly<br/>
… this also drifts closer to best practices<br/>
… do we want to recommend bit rates and formats, or do we want to leave it to the market?<br/>
Ivan Herman: I don’t fully understand the options<br/>
… there is the matter of the duration property, and what it’s value can be<br/>
… I’m not fond of the ISO format<br/>
… but I still use them<br/>
… I would be hesitant to invent our own format to replace the ISO one<br/>
… we shouldn’t do that<br/>
… we should just deal with the ISO format<br/>
… this is also the format recommended by schema.org<br/>
… so we should follow what they do<br/>
… we can raise the issue with schema.org at TPAC, and danbri will be at one of our sessions<br/>
… that is also true if we take the duration as a property for publicationLinks<br/>
… even if we have defined the object, we still need to be aligned with schema.org<br/>
… so no matter where we use duration, we should keep to what’s defined in ISO<br/>
Benjamin Young: <a href="https://www.w3.org/TR/html51/textlevel-semantics.html#the-time-element">https://www.w3.org/TR/html51/textlevel-semantics.html#the-time-element</a><br/>
Benjamin Young: html5’s time tag and datetime attribute all use ISO 8601, so it’s the prevailing winner<br/>
… even if you find it ugly<br/>
Ivan Herman: we do<br/>
Wendy Reid: no one is arguing, but we needed to bring it up to the larger group<br/>
… schema has a value for audiobooks, but it might be harder to extend to video<br/>
Ivan Herman: that’s a different question<br/>
</details>

**Comment by llemeurfr** [comment]
A note about the transcript of @BigBlueHat comment: the HTML time element supports either a date (using the W3C datetime format, which is a *subset* of the ISO 8601 format) or a duration. If it represents a duration, it can be formatted either using the ISO 8601 duration format or using a W3C custom format ("more readable" says the spec).

See https://www.w3.org/TR/2014/REC-html5-20141028/infrastructure.html#valid-duration-string 
more reading samples in e.g. https://developer.mozilla.org/fr/docs/Web/HTML/Element/time.
This means that "2 hours 15 mn" can be encoded either as `PT2H15M` or `2h 15m`.

Embracing the web would mean adopting this w3c syntax for durations, not the ISO syntax strictly speaking. 
This also means the schema.org is more restrictive than the w3c on the syntax of a duration.

**Comment by iherman** [comment]
@llemeurfr I have added this to https://github.com/w3c/wpub/wiki/Schema.org-issues. Hopefully we can discuss these at TPAC.

@wareid @TzviyaSiegman @GarthConboy

**Comment by HadrienGardeur** [comment]
Also FYI, in Readium we've decided to convert everything to seconds instead since that's what we're already using for:

- table of contents
- bookmarks
- current position in the audiobook

It feels easier to always work with seconds rather than juggle constantly between ISO 8601 for the primary reading order/metadata and seconds for everything else.

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2018/2018-10-22-pwg.html#section6-5).

- No actions or resolutions
<details><summary><i class="differentiate">View the transcript</i></summary>
6.5. audio duration<br/>
Ralph Swick: -> <a href="https://github.com/w3c/wpub/wiki/Schema.org-issues#duration-values">https://github.com/w3c/wpub/wiki/Schema.org-issues#duration-values</a> [audio] duration alues<br/>
Wendy Reid: duration in schema refers more to a CV - as in I was in a job from jan 2017 to feb 2018<br/>
… the html equivalent is more relevant than schema.org<br/>
Dan Brickley: see lower section of <a href="https://schema.org/Duration">https://schema.org/Duration</a> for properties whose value is datatyped schema.org/Duration, which does lean towards 8601<br/>
Ivan Herman: we should allow for the iso standard to be used<br/>
Ralph Swick: -> <a href="https://www.w3.org/TR/2018/WD-html53-20181018/infrastructure.html#durations">https://www.w3.org/TR/2018/WD-html53-20181018/infrastructure.html#durations</a> [HTML 5.3] Durations<br/>
Wendy Reid: we would like to extend the iso standard to be used<br/>
Dan Brickley: whereas <a href="https://schema.org/temporalCoverage">https://schema.org/temporalCoverage</a> covers date ranges, and we had some issue about openended ranges<br/>
Dan Brickley: <a href="https://github.com/schemaorg/schemaorg/issues/2086">https://github.com/schemaorg/schemaorg/issues/2086</a><br/>
Dan Brickley: next step is to follow up <a href="https://pending.schema.org/duration">https://pending.schema.org/duration</a> and clarify whether it is a temporal quantity, versus a period (temporalCoverage); could be clarified<br/>
6.6. additional vocabularies<br/>
Ivan Herman: general question - there is a large vocabulary for publications in schema.org, but new types of publications are unavoidable<br/>
… what steps should we take to add new types<br/>
Ralph Swick: -> <a href="https://github.com/w3c/wpub/wiki/Schema.org-issues#what-is-the-mechanism-this-community-should-follow-for-new-publication-types">https://github.com/w3c/wpub/wiki/Schema.org-issues#what-is-the-mechanism-this-community-should-follow-for-new-publication-types</a> mechanisms for new publication types?<br/>
Dan Brickley: we generally push to wikidata to do the work<br/>
Ivan Herman: proceedings is a good example<br/>
Dan Brickley: <a href="https://www.wikidata.org/wiki/Q1143604">https://www.wikidata.org/wiki/Q1143604</a><br/>
Dan Brickley: you can use wikidata directly<br/>
Ivan Herman: so in my json-ld, I would use Q1143604 instead of Proceedings?<br/>
Dan Brickley: yes<br/>
Ivan Herman: we could create an alias in the JSON-LD context file for the wikidata name<br/>
Dan Brickley: that too<br/>
Dan Brickley: workaround is “Proceedings” is a term in the surface syntax defined by a json-ld context, but maps to Q1234-style URLs<br/>
</details>

**Comment by danielweck** [comment]
Media Fragments URI ( https://www.w3.org/TR/media-frags/#naming-time ) normatively references RFC 2326 ( http://www.ietf.org/rfc/rfc2326.txt ), but note RFC 7826 https://tools.ietf.org/html/rfc7826
So we need to figure-out how to align here.

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2018/2018-10-23-pwg.html#section5-1).

- `RESOLVED:  Close issue #307 (duration) after discussion with schema, we will use NPT (Media Fragments) until they confirm or inform us otherwise research needs to be done`
<details><summary><i class="differentiate">View the transcript</i></summary>
Duration of an audiobook #307<br/>
Juan Corona: (chatter among the group) technical details<br/>
Daniel Weck: Media Fragment URI uses NPT Normal Play Time <a href="https://www.w3.org/TR/media-frags/#naming-time">https://www.w3.org/TR/media-frags/#naming-time</a><br/>
Ivan Herman: let’s stick to what we have now, because we ran out of time for the draft<br/>
Benjamin Young: latest Normal Play Time (NPT) RFC <a href="https://tools.ietf.org/html/rfc7826#section-4.4.2">https://tools.ietf.org/html/rfc7826#section-4.4.2</a><br/>
Daniel Weck: … ISO 8601 not suitable, hoping duration from Schema.org will be ammended <a href="https://en.wikipedia.org/wiki/ISO_8601#Durations">https://en.wikipedia.org/wiki/ISO_8601#Durations</a> (affects totalTime too from Schema)<br/>
Ivan Herman: introducing our own element now is not viable<br/>
Wendy Reid: let’s close this issue<br/>
George Kerscher: not sure if we need the duration for each chapter<br/>
… there’s the use case but people just want to know the book duration<br/>
… everything else could be calculated along, from the files<br/>
Wendy Reid: but there’s a track, we do get them as individual files, sometimes. but we get them as tracks instead most of the time<br/>
… it’s to get the best UX<br/>
… I want to know I’m 5 mins into a 25 min chapter for ex.<br/>
George Kerscher: so you get them as tracks.. you process them.. but what do you need?<br/>
Wendy Reid: it’s more complicated than that though<br/>
Juan Corona: it’s not 1:1<br/>
Brady Duga: my question is like george’s, wendy is this reflecting what’s current now?<br/>
… duration in the metadata is one form for us, but it’s not accurate. It’s concerning to have it like this<br/>
Wendy Reid: let’s talk about it, how does a pub look like when it’s packaged<br/>
Daniel Weck: bigbluehat RFC 2326 is referenced normatively by Media Fragment URI, do you suggest we explicitly reference RFC 7826 instead?<br/>
Wendy Reid: duration is on the chopping block I know, but we need it for the UX<br/>
Brady Duga: ToC, chapters mapped to the range of the chapters/tracks… you need to know how to calculate it.<br/>
Benjamin Young: DanielWeck: RFC 2326 states it’s obsoleted by RFC 7826, so I’d link to the newer one<br/>
George Kerscher: audio file sequence, you have a pointer to the beginning or the offset.<br/>
Brady Duga: if you have the info before hand you can calc it. but in the web you don’t know this info until you download it all<br/>
Romain Deltour: its a metadata issue, not a playback issue<br/>
Brady Duga: george you are right you can calc it, but it’s hard when you are streaming it<br/>
Wendy Reid: we need to know where in the chapter you are, with knowing the duration and offsets mixed with aggregation of the chapters or not<br/>
Lloyd Rasmussen: do we need to have an API and the player to coordinate this<br/>
Brady Duga: would the publishers give us this detailed ToC information?<br/>
Wendy Reid: the spec won’t eliminate this missing data, or bad data, but we can validate it and provide feedback<br/>
Daniel Weck: there are different ways to organize the files, theres a case theres a chapter with a title,<br/>
… or more sophisticated with a ToC, and files contain more than one chapter<br/>
… have the information on the manifest, along with the link<br/>
… any objections to this?<br/>
Wendy Reid: close issue with duration, use npt, until we get a new direction<br/>
Daniel Weck: media fragments has a different reference<br/>
Benjamin Young: there is a new one<br/>
Leonard Rosenthol: is it compatible with media fragments?<br/>
Benjamin Young: depends on what you are using, if npt> link,, to reference the new rfc coordinate with that group.<br/>
Wendy Reid: media fragments for now then<br/>
Resolution #1: Close issue #307 (duration) after discussion with schema, we will use NPT (Media Fragments) until they confirm or inform us otherwise research needs to be done<br/>
Benjamin Young: general question, not on the TF sorry.<br/>
… it’s not essential for pkg, its for navigation<br/>
… why is it in the manifest?<br/>
… it looks like annotation<br/>
Juan Corona: .. could it be on its own<br/>
Benjamin Young: someone could share this info like an annotation<br/>
… I feel like this content is not essential to the manifest, it could be tripped on<br/>
Wendy Reid: this is in the proper context though, this is out leading solution for now<br/>
Benjamin Young: there’s too much going on on many spaces<br/>
… a track in HTML5 is something else<br/>
… HTML wants a playlist system, it’s missing<br/>
… this is a good use case, to converge with.<br/>
Daniel Weck: this is the reading order<br/>
… page-list, audio streams<br/>
Wendy Reid: any objections to close this?<br/>
Daniel Weck: who edited the draft?<br/>
Ivan Herman: this is not for me, tbd in a PR<br/>
</details>

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2019/2019-04-08-pwg.html#section3).

- `RESOLVED:  Move the duration property to web publications`
<details><summary><i class="differentiate">View the transcript</i></summary>
duration in the context of WPUB<br/>
Wendy Reid: <a href="https://github.com/w3c/wpub/issues/307">https://github.com/w3c/wpub/issues/307</a><br/>
Wendy Reid: <a href="https://github.com/w3c/wpub/issues/420">https://github.com/w3c/wpub/issues/420</a><br/>
Wendy Reid: duration for entire content vs. duration at the resource level<br/>
Ivan Herman: duration currently defined in audiobook draft - nothing in there for duration is audiobook specific<br/>
… ability to add duration to a resource is generic - doesn’t have to be audio could be video or whatever else<br/>
… does it make sense to have a duration for the book as a whole? for audio books, it is a requirement, but not for a general web publication. but this may not be restricted to audio books. Maybe there could be a video book. The concept is generic, but it may be a requirement for audiobooks and not for general web publications.<br/>
Avneesh Singh: generic, but in audio profile should be compulsory. But what is duration of whole book? Does that include branches that are not included in the reading order?<br/>
Wendy Reid: Never seen a case where resources are not part of the reading order, but it could be possible. So we should include them in the entire duration.<br/>
Brady Duga: what is definition of accurate as far as duration? Want to make sure there is no requirement for the reading system.<br/>
Ivan Herman: what happens today?<br/>
Brady Duga: we determine the duration<br/>
Benjamin Young: agree with duga<br/>
Avneesh Singh: Duration is important metadata<br/>
Marisa DeMeglio: we will need this for sync media too; might not be a precise, e.g. user turns off page number announcements<br/>
Lloyd Rasmussen: agree that the reading system should manage those values<br/>
Ivan Herman: book level duration is more like general advisory information, not necessarily used by user agent for processing.<br/>
… if this is the case, then requiring it to be present sounds like a step too far. Should have/nice to have<br/>
… we have the duration set for an audio or video file. Is it required to provide that info as part of the resource description, or will reading system also ignore that?<br/>
Benjamin Young: <a href="https://schema.org/duration">https://schema.org/duration</a><br/>
Benjamin Young: we use schema.org duration property<br/>
… what is the point on insisting or not insisting… is it a requirement for reading systems? What is the use case we are trying to solve for?<br/>
Wendy Reid: top level duration is useful for user experience, e.g. product detail page. most commonly used on reading system side to break down chapters for example.<br/>
Brady Duga: we won’t use resource level durations but will pre-process all the audio to determine. But a web only reading system may not have this capability.<br/>
Wendy Reid: maybe the metadata is not used, but it can be provided in case the reading system can make use of it<br/>
Avneesh Singh: +1 to move to WP<br/>
Wendy Reid: should we move this to WP since it is not necessarily specific to audiobooks?<br/>
Proposed resolution: Move the duration property to web publications (Wendy Reid)<br/>
Benjamin Young: issue 420 - are we moving the requirement?<br/>
Ivan Herman: the term definition should be generic for WP, then we’ll discuss 420<br/>
Ivan Herman: +1<br/>
Garth Conboy: +1<br/>
Tim Cole: +1<br/>
Bill Kasdorf: +1<br/>
Laurent Le Meur: +1<br/>
George Kerscher: +1q+<br/>
Franco Alvarado: +1<br/>
Ben Schroeter: any opposition to the proposal to move to WP?<br/>
Ben Schroeter: vote<br/>
Ben Schroeter: +1<br/>
Brady Duga: +1<br/>
Avneesh Singh: +1<br/>
Resolution #2: Move the duration property to web publications<br/>
George Kerscher: ivan mentioned attribute about total duration - when a publication is time based media, then the total time would be very useful and I would examine it before downloading an audiobook<br/>
Joshua Pyle: +1<br/>
George Kerscher: like number of pages of a book<br/>
Benjamin Young: duration only allowed on audio books and media, but at the top level for creative works we could use <a href="https://schema.org/timeRequired">https://schema.org/timeRequired</a><br/>
… “estimated time to consume”<br/>
Ivan Herman: sounds like a great match<br/>
Benjamin Young: schema.org/timeRequired = “Approximate or typical time it takes to work with or through this learning resource for the typical intended target audience, e.g. ‘P30M’, ‘P1H25M’.”<br/>
Wendy Reid: interesting alternative. must think on it.<br/>
Ivan Herman: maybe we could in the WP document we make an explicit reference to time required at the top level and see if we can live with that, and keep the precise resource durations separate<br/>
Bill Kasdorf: +1 to distinguishing between timeRequired and duration<br/>
Wendy Reid: I will add to 420<br/>
George Kerscher: “Approximate reading time”<br/>
</details>
