### ISSUE TITLE
Clarify the coercion process from strings to objects in `Text Values or Objects`

### ISSUE THREAD

**Issue by BigBlueHat** [w3c/wpub#314]
Unless I'm *totally* missing something, the approach described in [Text Values or Objects](https://w3c.github.io/wpub/#strings-vs-objects) (and used throughout the examples) is not mappable to the terms as described there.

The examples in that section are below:
```json
{
    "author" : "Herman Melville"
}
```

```json
{
    "author" : {
        "@type" : "Person",
        "name"  : "Herman Melville"
    }
}
```

Those two are supposed to be equivalent according to that section. However, that's not possible in a JSON-LD context...afaik.

It *is* possible to say that `author` is always a `http://schema.org/name`, but it's not possible to "upgrade" that to a `http://schema.org/Person` with a `http://schema.org/name`...or to say the opposite--but it's not possible to allow for *either* shape within a single document.

**Comment by iherman** [comment]
I don't understand the problem. The value of "author" can be an object or a string; what's the problem? See, eg, [example on playground](
https://json-ld.org/playground/#startTab=tab-expanded&json-ld=%7B%22%40context%22%3A%22http%3A%2F%2Fschema.org%22%2C%22author%22%3A%5B%7B%22%40type%22%3A%22Person%22%2C%22name%22%3A%22my%20name%22%7D%2C%22your%20name%22%5D%7D). From JSON-LD point of view this is perfectly all right.

B.t.w., "name" is a property, not a class, ie, I am not sure this is relevant.

**Comment by akuckartz** [comment]
Interpreted as RDF the two examples seem to be quite different.

**Comment by iherman** [comment]
@akuckartz and they of course are. The value of the property is either a string or a resource with a different class. But that is perfectly fine RDF and, therefore, JSON-LD.

The fact that we "equate" the two approaches, more exactly that we consider a simple string as a shorthand of a particular class instance is an application domain issue, and not an RDF or a JSON-LD syntax issue. Note that the example from the playground is also accepted by the structured data testing tool for schema.org (except that a `"@type":"Book"`, or something similar, must be added to the top domain).

**Comment by iherman** [comment]
@BigBlueHat,

the terminology

>> In other words, a single string value is a shorthand for a `Person` object whose `name` property is set to that string value.

is probably misleading, which I believe is the source of confusion. @mattgarrish may help me out here to find the best formulation, but I guess it could/should say something like:

> In other words, a single string value is a shorthand *in a Web Publication Manifest* for a `Person` object whose `name` property is set to that string value.

(Emphasis is mine, we should not necessarily keep it that way in the text.) Maybe we could/should add something like

> It is _RECOMMENDED_ to use `Person` and `Organization` objects instead of the shorthand, to avoid misunderstandings.

(Again, I'd trust @mattgarrish to find the best formulation.)

Ie, 

> ...but I'm not sure if that's in the WebIDL or the JSON-LD or what...exactly.

it is actually none of the above, it is a modeling choice which has nothing to do with the JSON-LD per se, and the canonicalizaton makes these types of ambiguities disappear by the time it "gets" to an implementation of the WebIDL.

The reason I think we should do this is the usability argument: we should make simple things easy to express in the manifest. In many cases the only information the author wants to convey is simply the name of a person (e.g., `"author":"Herman Melville"`) and forcing the manifest author to create, instead, `"author":{"@type":"Person","name":"Herman Melville"}` would be considered as a major pain in the back, mainly for those who are not used to such modeling approaches.

---

The Schema.org situation is interesting. First of all, as you say, the tools do accept data with simple strings. How they exactly manage things inside is unknown to us, but I suspect they do essentially the same: internally they would transform strings into objects, maybe simply "Thing-s" (as shown on their online tool). The information is certainly _not_ considered to be an error in contrast to, e.g., providing a data without putting, say, a `"@type":"CreativeWork"` (or equivalent) on top.

Where it gets more interesting is that the do have this type of "shortcut" in their own examples. Look at, for example, at the JSON-LD representation of the third example of https://schema.org/Book, which includes the line:

```json
"publisher": "Little, Brown, and Company",
```

instead of using

```json
"publisher" : {
    "@type" : "Organization",
    "name" : "Little, Brown, and Company"
}
```

which, in our case, would indeed lead to the ambiguity that you refer to; they seem to be even more "lax" than we propose to be... But which also tell us that we SHOULD take this type of shorthand into account in any case.

There may be two possible actions (beyond the editorial ones above):

1. Leave things as is, emphasizing (possibly even more) that our internal model would lead to a `Person` in this case
2. We explicitly accept what schema.org does insofar as we generate a "Thing" in schema.org parlance, ie, for the Herman Melville example a simple string would be a shorthand for, simply, `"author":{"name":"Herman Melville"}`, ie, without a type. (Type is optional, not required). 

I am not very confortable with (2) but I can live with it if this is the group's decision.


(B.t.w., @HadrienGardeur was arguing for (2) before...)

**Comment by BigBlueHat** [comment]
First, thanks for the explanation. It does make things clearer.

> I am not very confortable with (2) but I can live with it if this is the group's decision.

The "magic" that Schema.org is doing (turning `author` and `publisher` into `name`'s on `Thing`s) does seem sensible...but also a bit out of keeping with the design of JSON-LD (et al)--as in, it picks a specific location (`name`), but doesn't tell anyone that it's going to do that. It seems very specific to the modeling done in Schema.org where everything is a `Thing` and consequently everything may have a `name`.

I suppose we can start with clarifying things, and see where we end up...

**Comment by BigBlueHat** [comment]
@iherman this seems to be the issue where a similar process was considered (and declined) in JSON-LD https://github.com/w3c/json-ld-syntax/issues/31 Maybe it would be a job for framing?

There isn't really a way to know if `"publisher": "qwepoiqwerj"` should be an `Organization` or a `Person`, and I'm not sure assuming `Person` makes sense...at least not for `publisher` (where the type expectations are opposite of those in `author`)... Anyhow...still musing on ways to improve the vagueness of the void. 😺

**Comment by iherman** [comment]
@BigBlueHat I propose closing; these things are now part of the 'canonical manifest' algorithm in the draft. There may be specific issues on the algorithm, but they should be in different issues.

Cc @TzviyaSiegman @wareid @GarthConboy

**Comment by iherman** [comment]
What is now called (@mattgarrish™) the "authored" manifest is a perfectly valid JSON-LD and even valid schema.org metadata. The "canonical" manifest is the result of some extra, WP-specific mapping that adds/expands data (not in the JSON-LD expansion sense, though). Any canonical manifest is, syntax and content wise, a valid authored manifest, although not vice versa. 

(If JSON-LD had some mapping/transformation language, the canonicalization could probably be defined in those terms...)

**Comment by wareid** [comment]
As discussed on Feb 4 2019, closing this issue as it's already addressed by the canonical manifest.
