### ISSUE TITLE
Mixed media in audiobook linear reading order

### ISSUE THREAD

**Issue by bduga** [w3c/wpub#322]
During a discussion of issue #320 the question of non-audio content (for example, HTML) in the linear reading order of an audiobook came up. Specifically, is that allowed, and if it is what is the expected behavior? Potential answers are "yes" and "we are specifying a format not behaviors". Discuss!

**Comment by danielweck** [comment]
Possible use-case (?): free audio book sample/preview, first two "chapters" only. The 'reading order' is composed of three items:

1) first chapter (link to audio resource `ch1.mp3`)
2) second chapter (link to audio resource `ch2.mp3`)
3) "buy me" page (link to HTML resource `gimme-more.html`)

I expect that the reading systems / specialised user agents which will implement support for the "audio profile" of web publications (packaged or not) will offer audio-centric user experiences (typical playback-oriented user interface). I suspect that some of these audiobook "players" may in fact *not* be capable of rendering web pages at all, either by design (e.g. mobile app with no built-in webview) or due to technical limitations (hardware device with physical buttons, basic visual display, or no screen at all).

A mobile app should be able to launch an external web "activity" (e.g. system / installed web browser) in order to present the "buy me" page to the user, assuming the `gimme-more.html` document and its associated resources are available online via a public URL. However, any authentication + credentials context would be lost when transitioning from the app to a standalone web browser, so I think this design pattern would be unrealistic in the real world. Plus, this would not work at all in the "packaged web publication" case.

So why not just state: "user agents / reading systems that do not support non-audio resources listed in the reading order should ignore/skip these resources"
?

**Comment by HadrienGardeur** [comment]
I think you're making several very good points @danielweck but this is a very complex issue:

- a WP could be a mix of HTML, audio, video and image resources in its reading order
- I don't think that all audiobook/comics reader will support HTML, far from it
- the most natural thing for them to do is to simply skip the resources that they can't support, but since we don't require `encodingFormat`, they won't necessarily know in advance the media type of a resource
- even UAs that fully support WP will have a hard time from a UX perspective dealing with the transition from an audio-centric UI to an HTML resource while following the reading order
- I expect UAs to sniff the type of the publication ("Audiobook" vs "Book") as well as the resources in the reading order to trigger different UIs

Based on all of these points, I think we should carefully consider an audiobook profile where:

- all resources listed in the reading order are audio resources
- the publication type is set to "Audiobook"
- HTML/images/videos are restricted to `resources` and `links`

Such a profile would be immediately (as in not in 2020+) useful for the industry (for the supply chain as well as end users), since there's a complete lack of standard format for audiobooks.

**Comment by llemeurfr** [comment]
Hadrien’s proposal seems really good. A UA which is able to switch between Audio resources and html resources will not stop when processing a « Book » publication, an audio-only UA will, as it will filter non « audiobook » publications.

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2018/2018-10-01-pwg.html#section1-3).

- No actions or resolutions
<details><summary><i class="differentiate">View the transcript</i></summary>
reading order<br/>
Ivan Herman: link: Issue 322<br/>
Wendy Reid: the last issue is #322<br/>
… it came out of #320 on mixed media and the reading order<br/>
… some audio books may have supplemental visual content<br/>
… often added as PDF or EPUB, but no UAs support this<br/>
… could a WP support this functionality? Should we have mixed media in reading order?<br/>
Ivan Herman: from the WP point of view, more difficult to restrict it than to have it<br/>
… we don’t have a restriction on the reading order–it can be any resource. PDF or drawing or whatever.<br/>
Garth Conboy: your statement is correct<br/>
… what happened with #320? Why is it ready to close?<br/>
Wendy Reid: because 322 addresses the question better<br/>
Garth Conboy: getting a PDF with a bunch of MP3 files is common<br/>
… so we’re in a good position with what we have<br/>
… the reading order would be a bunch of mp3s.<br/>
… then the other stuff would be in the “resources” as it’s supplemental<br/>
… . out of band auxiliary resources go in resources<br/>
… not sure about having other stuff in the reading order<br/>
Avneesh Singh: for 322, what garth said is right<br/>
… they were discussing the practicalities–what if the reading system doesn’t support PDF?<br/>
… what should reading system do if the media isn’t supported?<br/>
… Hadrien mentioned a profile for audio books, where the reading order might be audio-only<br/>
Brady Duga: avneesh hit on my issue<br/>
… should we say what happens when these things happen in the reading order<br/>
… I like allowing these things<br/>
… but I don’t know how far we should go in the spec to require certain behaviors<br/>
… I don’t want to prevent innovation<br/>
Joshua Pyle: I agree with that<br/>
… to avneesh’s point on what if a reading system doesn’t support PDF<br/>
… a web publication should support anything the web supports<br/>
… but what if Alexa comes across a PDF? What happens?<br/>
… we can’t say what every implementation will do<br/>
Ivan Herman: back to one comment by Avneesh about profiles<br/>
… in a sense I could say we already have them, just not by name<br/>
… we require the type of publication in the manifest<br/>
… a reading system looking at the type can find out that it is an audiobook<br/>
… we already say that certain schema terms only make sense in certain contexts<br/>
… no need to make things more confusing<br/>
Benjamin Young: I’d agree with ivan<br/>
… I’d also like to mention atom and rss, which started as text-only but then podcasting happened, and now both formats represent both audio and text, and possibly intermixed<br/>
… and you’d just listen to audio if your device has no screen<br/>
… but on some other device you could consume both types of content<br/>
… so we don’t need to overly constrain the world<br/>
… we don’t want the types to constrain things.<br/>
George Kerscher: I agree with the ideas of not limiting innovation<br/>
… with AR, VR, etc<br/>
… however, if a reading system ignores what it doesn’t understand, the audio book would be understandable if you just consumed the audio portions<br/>
Wendy Reid: that’s the assumption that most user agents make with audiobooks<br/>
… we just don’t offer the supplemental content, for example<br/>
… we don’t want to stifle innovation. Supplemental content is important.<br/>
</details>

**Comment by llemeurfr** [comment]
The following is IMO a proper way to solve this issue:
The spec states that an Audiobook publication SHOULD contain audio resources only in its reading order. 
And it is not expected from UAs supporting this profile that other types of resources will be played/read (be it in the reading order, resources or links). 
A non-normative note adds that other types of ressources MAY be present in an Audiobook so that advanced UAs may make use of them; and  that in such case it is recommended to insert them in "resources".

The SHOULD means that the schema will not constrain the resource type for an Audiobook.  We don't constrain the behavior of the UA but we state expectations (non-expectation in this case).

**Comment by HadrienGardeur** [comment]
One of the most important thing is the ability to detect when the context should switch to "audio-only" or "mostly-audio".

With our current specification, we can't look at the `readingOrder` and know what to expect since it won't necessarily contain any information concerning the media type of our resources (something that I still find problematic).

We could of course fetch every single resource to figure out what's returned, but this is not the most effective way of dealing with this issue.

Inspecting the value of `type` is therefore a good fallback and it seems reasonable to expect audio in the reading order when it is set to `Audiobook`.

I don't know if we'll end up with a specific profile or just a best practice document (that's up to the Audiobook TF to decide cc @wareid), but this should be within the scope of such documents.

**Comment by iherman** [comment]
> We could of course fetch every single resource to figure out what's returned, but this is not the most effective way of dealing with this issue.

I would be fine to restrict the current approach described in [the current draft](https://w3c.github.io/wpub/#arrays-and-single-values) so that we would have a series of common suffixes that the processor would recognize to set the media type (after all, these suffixes are part of the media type registration) and the processor would remove all the other ones. I believe that if we do recognize html, svg, jpeg, png, gif, mp3 and maybe a few more common datatypes, we would keep the goal of simplicity for the usual cases and would make the life of implementations easier.

Note, however, that in general, and unfortunately, the only secure way is to fetch the resource and see what is returned, because even if `PublicationLink` objects are used instead of simply URL-s, the media type may be missing or simply wrong. The Web is messy...

**Comment by HadrienGardeur** [comment]
> I would be fine to restrict the current approach described in the current draft so that we would have a series of common suffixes that the processor would recognize to set the media type (after all, these suffixes are part of the media type registration) and the processor would remove all the other ones

I'm not a super big fan of that approach either:

- there's no requirement to use a suffix on the Web, your URI could be whatever you want them to be
- we'd like to avoid setting the list in format in stone as mentioned in #323

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2018/2018-10-23-pwg.html#section5-3).

- No actions or resolutions
<details><summary><i class="differentiate">View the transcript</i></summary>
Wendy Reid: <a href="https://github.com/w3c/wpub/issues/322">https://github.com/w3c/wpub/issues/322</a><br/>
Wendy Reid: issue 322 mixed media<br/>
… audiobook readers don’t support supplemental content (sc)<br/>
Laurent Le Meur: WP can help supporting sc<br/>
Wendy Reid: the topic is important for the WG as a whole<br/>
… publisher will probably mix content in WP even if this is not stated good practice.<br/>
… an ad could be insterd in the middle of an audiobook<br/>
Hadrien Gardeur: my concern is that we won’t be able to easily identifiy such supplemental content<br/>
… the UA will discover it when it tries to fetch it.<br/>
Brady Duga: maybe not too bad. Some annoying cases will arise. And there is no processing model defined.<br/>
… A use case may be show a picture of a character + play the corresponding audio<br/>
… but without processing model, we don’t know what to do.<br/>
<b>Juan:</b> why don’t specify a duration with an image?<br/>
George Kerscher: we could put the image in the ToC.<br/>
… but it’s going in the sync media model<br/>
Ivan Herman: I don’t understand. Each item in the reading order has a media-type.<br/>
… the media-type may be wrong but specification wise, this is a fact.<br/>
Hadrien Gardeur: therefore for an audiobook it”s a requirement to add a media-type. I’m ok.<br/>
Marisa DeMeglio: this sounds like a case for sync-media. Pure audiobook and sync-media should have proper overlap so that audiobooks can get such bells and whistles.<br/>
Garth Conboy: the generic case is a business book with tables, and a pdf.<br/>
George Kerscher: we could do it with a ToC.<br/>
Wendy Reid: it conrresponds to a use case in which the ToC has images.<br/>
Ivan Herman: in fact in the current spec there is no default, I was wrong. Maybe we should say that a resource should be an html (by default), if no media type is given. In an audiobook each item would therefore require a media-type.<br/>
Hadrien Gardeur: the problem is only when there is mixed content. It would be reasonable that if a WP is typed “audiobook”, it should contain only audio files.<br/>
Proposed resolution: if a string appears in readingOrder/resources/links, the canonical manifest should include a Publication link for that URL signaled as text/html (Ivan Herman)<br/>
Wendy Reid: or if all resources are audio files the UA sees it as an audiobook and treat it differently than a generic ebook.<br/>
Avneesh Singh: Audio book may be a profile, which allows to say that it is recommended to have audio content in default reading order<br/>
Proposed resolution: if a string, or a PublicaitonLink without encoding format, appears in readingOrder/resources/links, the canonical manifest should include a Publication link for that URL signaled as text/html (Ivan Herman)<br/>
Brady Duga: you say that by default, even for an “audiobook”, the content is html. This would make a stupid format.<br/>
Ivan Herman: how to be sure the content is an audio file only from its media type?<br/>
Daniel Weck: we’re deviating from the web, where the media-type triggers behaviour in the UA<br/>
Ivan Herman: previous proposal resjected ;-)<br/>
George Kerscher: does epubcheck goes through an confirms the media type of content?<br/>
Ivan Herman: if there is no explicit media type there is no checking.<br/>
Daniel Weck: the same remarks we made about mixing content applies to comics also.<br/>
Benjamin Young: this discussion is not great for web browsers<br/>
Benjamin Young: to DanielWeck’s point: {"@context": "<a href="http://schema.org/",">http://schema.org/",</a> "@id": "<a href="http://w3.org/",">http://w3.org/",</a> "@type": "AudioBook"} is correct (but rather insane) JSON-LD<br/>
Daniel Weck: where to I get the information of book vs audiobook? the audiobook type in the manifest just states the schema.org schema will validate some metadata.<br/>
Laurent Le Meur: the meaning of “audiobook” should be stronger than that and indicate also that it contains audio<br/>
Daniel Weck: for sync-media we use “audiobook” with html content.<br/>
… I’ll open an issue.<br/>
Hadrien Gardeur: hint should not be trusted. You should prepare for fallback when something goes wrong.<br/>
</details>

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2019/2019-02-25-pwg#section2).

- No actions or resolutions
<details><summary><i class="differentiate">View the transcript</i></summary>
2. Mixed media in audiobook linear reading order (Issue 322)<br/>
Wendy Reid: <a href="https://github.com/w3c/wpub/issues/322">https://github.com/w3c/wpub/issues/322</a><br/>
Wendy Reid: Some of this is complicated by the TOC situation. We have 6 open issues that are tagged as audio issues.<br/>
Wendy Reid: There was a discussion about the reading order - there is no restriction as to what can be in the reading order. We were wondering if in audiobooks, since it has a use case of being mainly audio, but sometimes it contains supplemental info (pictures, charts, etc)…<br/>
… would that be considered a resource or part of the reading order? It’s innovative/wishful thinking. Based on the discussion. The likely best resolution is that it should be considered as not-part-of-the-reading-order<br/>
Ivan Herman: I don’t fully understand as I was not part of the discussion. Why do we need to specify? Why isn’t it something that the author can supply/note?<br/>
Wendy Reid: It’s a decision we have to make. I’m pro having it in the reading order, but the issue could come down to the reading order. The User-agent could end up not showing it. That is another option we have to consider.<br/>
… It might be easier to say: “these are all resources”<br/>
Benjamin Young: I don’t like sub-typing. I prefer to keep things consistent — so readers with varying skills can play and handle only what they know. If you have a screen, it can show you what you want, otherwise not. As a spec, we already accommodate it<br/>
Laurent Le Meur: I would like to have authors coming back to developers — they say: “your system doesn’t work as it doesn’t show HTML when playing audiobooks” We have to set expectations. There is no expectation that a classic audiobook will render HTML.<br/>
… I understand that some special reading agents would be able to read something else. Standard one would not. We should have expectation that it SHOULD be audio files, and it’s expected that a reading system can handle that, and everything else should be in resources. We can let the JSON schema be open to any resource…<br/>
… but expectations should be clearly set.<br/>
Garth Conboy: q<br/>
Marisa DeMeglio: I don’t have a strong opinion if audiobooks should include other resources, but is this issue about having no playback model for non audio files?<br/>
Wendy Reid: There is no model, at least not for now…<br/>
Marisa DeMeglio: A resource in the middle of playing audio — you don’t know how long you should keep it up on the field…<br/>
Garth Conboy: There is a class of audiobooks today — that come with a PDF or bunch of PDFs that are ancillary material. There’s not expectation for them to render along with the content, or that a reading system is to show it, but the content is to be bundled…<br/>
… so a user’s action is to look at the supplemental content. We need to have the ability to have those types of audiobooks to be produced, but we should allow supplementary material<br/>
Ivan Herman: I’m trying to combine those issues with others that are around — there may be other connections. If we say that an audiobook is defined that everything in the reading order must be an audio file. Which is fine — it’s a sensible definition for a well-existing market…<br/>
… if we do that, nevertheless, there is a need for books that have a mixture of the various media for a bunch of other reasons. They are web publications, but they are not audiobooks. Audio still has items open about items in the manifest - readBy, etc.. All those properties should not be in the audiobook profile…<br/>
… they renamed general properties that are relevant to audio. If we are strictly audiobooks, then everything related to describing the audio items, they need to be generally available, because they could describe items generally available.<br/>
Wendy Reid: <a href="https://github.com/w3c/wpub/issues/351">https://github.com/w3c/wpub/issues/351</a><br/>
Tzviya Siegman: Based on Garth and some email descriptions and from HC — I’m a bit confused about supplemental materials. If the method is a URL that the publisher provides, how does the user see it? Is it HTML? I don’t know what Google does, but I know it’s a huge problem.<br/>
Wendy Reid: Publishers are providing a PDF file — I’ve yet to see anything but PDFs. Right now, if a customer asks for it, we can send it, but we don’t have a good way to deliver it. It’s a very awkward system if you’re using a reading system or an app. There’s no way to surface a URL.<br/>
Tzviya Siegman: If we have a method of conveying HTML to a user — we have a solution for ToC<br/>
Garth Conboy: I agree with what Wendy said, on our initial implementation — a user contacted us and we sent the PDF. Right now our listening system surfaces in the player “open supplemental” and we deliver the PDF behind the scenes so the client can click to open…<br/>
… it works very well. What we need to do — capability wise — is that we need to allow the supplemental PDF to tag along with the content. If the reading system has way to deal with it… Publishers need to be able to package the material and it’s up to<br/>
… the reading system to implement<br/>
Nick Ruffilo: I agree with a lot of what’s been said. I think if we go with a web publication with audio and other stuff interspersed, versus just audio… If we give the user the option to download the supplements and letting them know… I’m failing to see why that would be a bad thing.<br/>
Tzviya Siegman: It sounds like with the existing workflows — this isn’t something that exists today. Maybe we should hold off on spec’ing out. It’s a problem, but maybe it’s something we defer until we understand the scope of the issue.<br/>
Wendy Reid: To clarify, this issue is about — every discussion the audiobook group talks about, it should include supplemental content. Knowing that not all reading systems will render it. So the question is if the supplemental content should be in the TOC or resource only<br/>
Wendy Reid: <a href="https://github.com/w3c/wpub/issues/351">https://github.com/w3c/wpub/issues/351</a><br/>
Garth Conboy: +1 Wendy<br/>
Wendy Reid: so if we use the type specifically, the audiobook TYPE would only see audio files in the TOC><br/>
Benjamin Young: I’m not sure what the distinction. Why split the hair? If you have the ability to skip a file that you didn’t understand. If you stuck in a resource that it doesn’t understand. It either fails, or sees what is next and keeps going — possibly with mention that it had to skip.<br/>
… RSS and ATOM feeds that distribute podcasts have a very similar data model. Those can mix and do often mix. You’ll have a text blog, media blog, etc. The podcast consumer will only process the audio ones. A richer RSS reader will process all…<br/>
… We shouldn’t limit the resources, but include resources and information that gives implementors what to do with the files, but we should try not to limit ourselves and paint ourselves into a corner.<br/>
Garth Conboy: I agree with what Wendy said before — we have to allow for supplemental materials. If they are in the reading order or other resources. I lean towards other resources, but it’s just an opinion. To harken back to early EPUB discussion, it can always just skip resources.<br/>
Avneesh Singh: This has some TOC dependency. Reading order and TOC are different items - they may or may not have overlap. It’s possible the default reading order keeps just audiofiles and the HTML TOC has all<br/>
George Kerscher: I get that novels are traditionally what is done today, but we should open to a wider range of materials. Magazines — yes there’s a reading order, but more likely I want to go to article 6 etc. A book of poetry — human narration of poetry is much better than machine read poetry…<br/>
… I don’t want to read poetry book cover to cover, but to navigate to the poem, bookmark, etc. If we ignore this market of different types of publishing, then it gets relegated to someone figuring out how to put together a bunch of podcasts.<br/>
Mateus Teixeira: +1 George… I’ve even seen requests for audio-textbooks<br/>
George Kerscher: so we want to come up with something that does all these types of publications.<br/>
Nick Ruffilo: +1 to mateus with the audio-textbooks<br/>
</details>

**Comment by wareid** [comment]
PROPOSAL: Leave mixed media content out of the `readingOrder` and specify that supplemental content live in `resources`. This will allow it to be referenced in the TOC, but if a user agent cannot support it, it can be skipped.

**Comment by iherman** [comment]
@wareid: is it a _SHOULD_ or _MUST_? I mean is it

> If the publication is of type `audiobook`, then the reading order _MUST NOT_  include any content other than audio.

or is it _SHOULD NOT_? The behaviour of the user agent is very different.

**Comment by wareid** [comment]
Resolution: Leave mixed media content out of the readingOrder and specify that supplemental content live in resources. This will allow it to be referenced in the TOC, but if a user agent cannot support it, it can be skipped.

There will be issues opened to address the TOC and rel questions.

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2019/2019-03-04-pwg.html#section1-2).

- `RESOLVED:  Leave mixed media content out of the readingOrder and specify that supplemental content live in resources. This will allow it to be referenced in the TOC, but if a user agent cannot support it, it can be skipped.`
<details><summary><i class="differentiate">View the transcript</i></summary>
1.2. Issue #322: Mixed media in audiobook linear reading order<br/>
Wendy Reid: <a href="https://github.com/w3c/wpub/issues/322">https://github.com/w3c/wpub/issues/322</a><br/>
Wendy Reid: the proposal is to leave mixed media content outside of the reading order<br/>
… but keep it in the resources list<br/>
… so it doesn’t get shown unnecessarily<br/>
… this would be a MUST<br/>
… so only audio content would be in the reading order<br/>
Resolution #3: Leave mixed media content out of the readingOrder and specify that supplemental content live in resources. This will allow it to be referenced in the TOC, but if a user agent cannot support it, it can be skipped.<br/>
Wendy Reid: everything else would be in the extra resources<br/>
Benjamin Young: How does a reading system know to make use of any of these resources?<br/>
Wendy Reid: Really good question — and not one solved currently by audiobooks — we say if the user opens them they open them<br/>
Benjamin Young: I’m wondering how they know they are there. Publications concede dependencies across multiple resources. The cover, additional notes, tabs, whatever you might want to put — because of that, there’s no binding or way to say where they go or how they should show up<br/>
… so the reader or User Agent wouldn’t know what to do with them. That seems like - not like what is actually wanted here.<br/>
Wendy Reid: This came up — when we discussed last time…<br/>
Tzviya Siegman: it’s basically just saying here’s a link to your thing<br/>
… with no statements of how it should be displayed<br/>
… we don’t explain how to process links<br/>
… and we don’t need to get into the details of that<br/>
Laurent Le Meur: in the example of a cover<br/>
… there’s a rel attribute that says this is a cover<br/>
… the user agent will know what to do with that<br/>
… it could be the same for a pdf containing something useful<br/>
… we could create a vocabulary of uses<br/>
… to instruct the UA what it should do with them<br/>
… without it being a requirement<br/>
George Kerscher: if there’s a MUST here for these not to be in the reading order<br/>
… is there a MUST that they should be pointed to from a ToC?<br/>
… otherwise how would they be utilized?<br/>
Wendy Reid: this is then related to the ToC conversation then<br/>
… laurent_ brings up a really good point about the rel attributes<br/>
… perhaps someone can make an issue for how to express supplemental content<br/>
Laurent Le Meur: ok. I can do that<br/>
Wendy Reid: I think it deserves it’s own discussion<br/>
Laurent Le Meur: I just wanted to say that a vocabulary of rel as a best practice is useful<br/>
… I think we shouldn’t go toward excluding content<br/>
… I will first open the rel attributes for audiobooks<br/>
Wendy Reid: I don’t think this blocks the issue though from being closed<br/>
Avneesh Singh: Should we have another issue for George’s recommendation<br/>
Tzviya Siegman: I agree with wendyreid and ask George to open a new issue<br/>
Benjamin Young: I think pivoting on types is dangerous and moves us away from the work we’ve done - and coming up wiht a generic model. We’re trending to n+1 possible types with possible processing instructions. If the RELs are valuable for cover, they can’t be best practices, they have to be known to the reading systems…<br/>
… It needs to be part of the data model if we expect it to be part of the data model - otherwise it is constructed however… I’m concerned with a lot of this being under specified and under-planned and not addressing accessibility and UA usage…<br/>
… and what the expected behavior would be if a UA sees this. You’d have a reading order thing, a resources thing, some of which is valuable, some of which is not - and it’s oddly constructed without clear intentions across different agents.<br/>
Tzviya Siegman: I want to be sure we don’t backtrack<br/>
… I believe we came to a conclusion about rel values in resources<br/>
… I think we need to have that chat there, and not as part of this issue<br/>
… we could ask the question about how a UA knows to render anything<br/>
… we’re focusing right now on whether the audio book profile<br/>
… and what to do with these extra resources<br/>
… and we should consider this in light of any web publication<br/>
… right now, there’s no specification about how these things are handled<br/>
… my expectation is that these would simply open in a browser<br/>
… but we should discuss these in the context of that rel issue<br/>
… I think George should open that ToC issue, because that is a valid concern<br/>
Wendy Reid: George could you open an issue for your question then?<br/>
George Kerscher: sure<br/>
</details>
