### ISSUE TITLE
List of recommended audio formats for audio-only WP

### ISSUE THREAD

**Issue by avneeshsingh** [w3c/wpub#323]
In EPUB 3 we had notion of core media types. I think that we should not try to restrict audio-only WP in such a way. At the same time it is also true that support for various audio formats vary from browser to browser. 
So, to help publishers in producing audio publications that work well with popular browsers, we should come up with a list of recommended audio formats for audio-only WP.

**Comment by llemeurfr** [comment]
Note: a browser compatibility list for audio formats can be found at 

https://caniuse.com/#feat=audio (look at sub-features, add https://caniuse.com/#search=webm)

Seems that today, MP3 (low quality), AAC (flexible) and FLAC (lossless) have proper support in most browsers. Not really true for Ogg-vorbis and WebM so far. 

I also found: 

https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats#Browser_compatibility 

https://developer.mozilla.org/en-US/docs/Web/Apps/Fundamentals/Audio_and_video_delivery/Cross-browser_audio_basics#Audio_Codec_Support

**Comment by lloydrasmussen** [comment]
If you search CanIUse.com for Opus, the support looks a little better. This audio codec is supported by enough web browsers and operating systems that it should be considered, especially in situations where file size and transport/storage requirements are important.

**Comment by llemeurfr** [comment]
@lloydrasmussen, yes Opus is streamable and supported by Firefox, Chrome, Edge. The missing kid is Safari (I just tried http://opus-codec.org/examples/, see "Example of use in a web page"). But still it can be a recommended format. 

I agree that we should not try to keep "core media type", i.e. imposed fallbacks, but rather recommend media types compatible with Web usage. I would prefer if it was expressed via articles (best practices, some evolution of "EPUB Secrets") rather than in the WP spec.

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2018/2018-10-01-pwg.html#section1-2).

- No actions or resolutions
<details><summary><i class="differentiate">View the transcript</i></summary>
Ivan Herman: link: Issue 323<br/>
Wendy Reid: the other issue is bitrate and format<br/>
… there’s a secondary issue, #323, logged by Avneesh<br/>
… there are innumerable ways to encode audio…mp3, flac, opus, etc<br/>
… and many different bitrates<br/>
… in EPUB 3 we had the idea of core media types<br/>
… with WP, do we want to express recommended media types, more best-practices?<br/>
Ivan Herman: what does HTML say about the audio element, in terms of bitrate and format?<br/>
… we should should push the corpse into someone else’s courtyard<br/>
Avneesh Singh: audio element in HTML accepts a broad set of formats<br/>
… but popular browsers may use a smaller set<br/>
… we should not restrict WP in the way we restricted EPUB<br/>
… we should not have core media types<br/>
… but we do need to recommend formats for audio publishers which will actually work<br/>
… the only question is how to present this information? It could be in a non-normative document<br/>
… note I’m not mentioning EPUB4 here<br/>
George Kerscher: there are issues where human audio is in a smaller bandwidth than music<br/>
… so some formats are better for human audio<br/>
… and variable bitrates can make it more difficult to seek to a particular place<br/>
… and the available of time scale modification, to speed up or slow down without changing pitch<br/>
Wendy Reid: by identifiying use cases maybe we can find some recommendations<br/>
Benjamin Young: this is HTML’s section on mime types, which is more generous than what you’d find in EPUB<br/>
… this also allows for innovation and progress, because it is not restrictive<br/>
… let’s keep the web in web publications :)<br/>
Joshua Pyle: looking at George’s use cases for seeking and time scale modification… do we have these use cases? Should we add them to the general use cases doc?<br/>
Wendy Reid: we should have audio-specific use cases<br/>
Ivan Herman: one more source to look at…<br/>
… there are two related groups at W3C<br/>
… there’s the audio working group<br/>
… but what might be more interesting is the media and entertainment interest group<br/>
… it grew out of webtv but went beyond that<br/>
… at the Tokyo workshop the team contact was there, and I tried to convince him to join our F2F meeting<br/>
… so we could talk to him there<br/>
… I think we already discussed that we would not have a restriction on web publications–whatever works on the web works for us<br/>
Wendy Reid: some of these issues could be cleared up by use cases. We’ll discuss in the task force.<br/>
</details>

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2018/2018-10-01-pwg.html#section1-3).

- No actions or resolutions
<details><summary><i class="differentiate">View the transcript</i></summary>
reading order<br/>
Ivan Herman: link: Issue 322<br/>
Wendy Reid: the last issue is #322<br/>
… it came out of #320 on mixed media and the reading order<br/>
… some audio books may have supplemental visual content<br/>
… often added as PDF or EPUB, but no UAs support this<br/>
… could a WP support this functionality? Should we have mixed media in reading order?<br/>
Ivan Herman: from the WP point of view, more difficult to restrict it than to have it<br/>
… we don’t have a restriction on the reading order–it can be any resource. PDF or drawing or whatever.<br/>
Garth Conboy: your statement is correct<br/>
… what happened with #320? Why is it ready to close?<br/>
Wendy Reid: because 322 addresses the question better<br/>
Garth Conboy: getting a PDF with a bunch of MP3 files is common<br/>
… so we’re in a good position with what we have<br/>
… the reading order would be a bunch of mp3s.<br/>
… then the other stuff would be in the “resources” as it’s supplemental<br/>
… . out of band auxiliary resources go in resources<br/>
… not sure about having other stuff in the reading order<br/>
Avneesh Singh: for 322, what garth said is right<br/>
… they were discussing the practicalities–what if the reading system doesn’t support PDF?<br/>
… what should reading system do if the media isn’t supported?<br/>
… Hadrien mentioned a profile for audio books, where the reading order might be audio-only<br/>
Brady Duga: avneesh hit on my issue<br/>
… should we say what happens when these things happen in the reading order<br/>
… I like allowing these things<br/>
… but I don’t know how far we should go in the spec to require certain behaviors<br/>
… I don’t want to prevent innovation<br/>
Joshua Pyle: I agree with that<br/>
… to avneesh’s point on what if a reading system doesn’t support PDF<br/>
… a web publication should support anything the web supports<br/>
… but what if Alexa comes across a PDF? What happens?<br/>
… we can’t say what every implementation will do<br/>
Ivan Herman: back to one comment by Avneesh about profiles<br/>
… in a sense I could say we already have them, just not by name<br/>
… we require the type of publication in the manifest<br/>
… a reading system looking at the type can find out that it is an audiobook<br/>
… we already say that certain schema terms only make sense in certain contexts<br/>
… no need to make things more confusing<br/>
Benjamin Young: I’d agree with ivan<br/>
… I’d also like to mention atom and rss, which started as text-only but then podcasting happened, and now both formats represent both audio and text, and possibly intermixed<br/>
… and you’d just listen to audio if your device has no screen<br/>
… but on some other device you could consume both types of content<br/>
… so we don’t need to overly constrain the world<br/>
… we don’t want the types to constrain things.<br/>
George Kerscher: I agree with the ideas of not limiting innovation<br/>
… with AR, VR, etc<br/>
… however, if a reading system ignores what it doesn’t understand, the audio book would be understandable if you just consumed the audio portions<br/>
Wendy Reid: that’s the assumption that most user agents make with audiobooks<br/>
… we just don’t offer the supplemental content, for example<br/>
… we don’t want to stifle innovation. Supplemental content is important.<br/>
</details>

**Comment by geoffjukes** [comment]
Blackstone is evaluating Opus for it's lossy archive format (replacing AAC). We use FLAC for the lossless archive format.

**Comment by wareid** [comment]
PROPOSAL: The Audiobooks profile will not include a recommended list of audio formats for audiobooks. We will leave this in the hands of the content creators.

**Comment by geoffjukes** [comment]
Ever heard of ALS audio? No? There is exactly ONE implementation for encoding it.... and the Library of Congress chose it as their lossless archive format.

@wareid I agree with not being overly proscriptive here, but my concern is that if it is left too open, a publisher might go nuts. Some guidance could help. Would it be reasonable to "Recommend audio formats supported by HTML5 Audio" or something?

https://en.wikipedia.org/wiki/HTML5_audio

**Comment by llemeurfr** [comment]
It may be a community best practice document instead of a WG list, if the latter seems too much prescriptive, but there is definitely a need to express that mp3 is not the ultimate audio format, forever.

**Comment by avneeshsingh** [comment]
There are many audio formats in the world, so I think that providing some guidance is important to help publishers in identification of audio formats that have wider acceptance.
I would propose maintaining a non-normative list that can be updated frequently. It may be a separate document referenced by audio pub specs.

**Comment by iherman** [comment]
I would be wary of setting up our own list... such lists, if not correctly maintained, become a hurdle eventually. Falling back on an existing community effort would be much better imho.

I am not familiar with this world; @geoffjukes is the wikipedia article you referred to (https://en.wikipedia.org/wiki/HTML5_audio) an authoritative source in this community? It was last edited a few weeks ago, which is a good sign. On the other hand, I did not find any reference to it (or to anywhere else) in the html spec (but I may have missed it).

**Comment by avneeshsingh** [comment]
@iherman , the main objective behind having a non-normative document linked from specs is to ensure its visibility. Separate documents are difficult to find. If we can ensure that one can easily locate best practices document it is fine. May be we should have links to such documents in introduction section of specs, or may be at some other place where these are clearly visible.

**Comment by geoffjukes** [comment]
@iherman Not my area of expertise either, though I did find this: https://www.w3.org/wiki/Html/Elements/audio#Formats_and_Codecs

Which itself references the Wikipedia page.

**Comment by wareid** [comment]
I think an accompanying "Best Practices" document is in the works here ;). I agree we should offer some guidelines, maybe that is the best way. It will certainly be a lot easier to keep up to date, and we can work with publishers/distributors to communicate the latest in recommendations or support. I just think for the spec we're being too prescriptive.

**Comment by wareid** [comment]
RESOLVED: The Audiobooks profile will not include a recommended list of audio formats for audiobooks. We will leave this in the hands of the content creators. We will reference the supported formats from HTML5's <audio> element.

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2019/2019-03-04-pwg.html#section1-3).

- `RESOLVED:  The Audiobooks profile will not include a recommended list of audio formats for audiobooks. We will leave this in the hands of the content creators. We will recommend the list of supported types under HTML5 <audio> specifications.`
<details><summary><i class="differentiate">View the transcript</i></summary>
1.3. Issue #323: List of recommended audio formats for audio-only WP<br/>
Wendy Reid: <a href="https://github.com/w3c/wpub/issues/323">https://github.com/w3c/wpub/issues/323</a><br/>
Wendy Reid: this is about recommend formats for audiobooks<br/>
… we plan to leave this in the hands of content creators<br/>
… as discussed in the issue, by making this decisions<br/>
… we also intend to point to something we can keep up to date<br/>
Proposed resolution: The Audiobooks profile will not include a recommended list of audio formats for audiobooks. We will leave this in the hands of the content creators. (Wendy Reid)<br/>
Wendy Reid: but we don’t want to prescribe what the industry is probably already doing for themselves<br/>
Dave Cramer: one of the reasons we have specs at all is to facilitate interoperability<br/>
… if I create something that follows the spec, then I can have some expectation that a supporting client can handle it<br/>
… I fear we’re bypassing interoperability here<br/>
… if I make one using MP3, then do I risk it not being useful in some of the readers?<br/>
… am I then required to read all the docs of all the readers to figure it out?<br/>
Wendy Reid: I think that’s why we’re hoping to have a living list of formats that we keep up to date long term<br/>
… for instance, opus which is widely supported, but not supported by everyone would everywhere<br/>
… but we don’t want to limit it<br/>
Tzviya Siegman: I did like Geoff’s suggestion on github<br/>
… limiting audio (and eventually video) to those things supported by the &lt;audio> (and <video>) element<br/>
… then it’s not our fault for being to restrictive…it’s those HTML people<br/>
George Kerscher: is there a notion here that an audio publisher would send to their distributor something that is not compressed?<br/>
… and then the distributor figures out what they want for distribution?<br/>
Wendy Reid: geoffjukes might have a better perspective on that specifically<br/>
Geoff Jukes: we can deal with anything that fmpeg can read<br/>
… but then we convert it to things our apps can understand<br/>
… we accept anything right now<br/>
George Kerscher: do you concern yourself with things that are encoded?<br/>
… and then decode, and re-encode it at the risk of loss of quality?<br/>
Geoff Jukes: we have a list of preferred codecs in descending order<br/>
… we prefer lossless first<br/>
… all the way down to “or whatever you’ve got” (literally)<br/>
… in the transcoding process we force it into a uniform output<br/>
… so we encode it into M4A’s for kobo and our apps, MP3s for audible, etc<br/>
… doing this for audiobooks is less of an issue than doing this with orchestral music, for instance<br/>
Wendy Reid: is there any opposition to closing this issue<br/>
Resolution #4: The Audiobooks profile will not include a recommended list of audio formats for audiobooks. We will leave this in the hands of the content creators. We will recommend the list of supported types under HTML5 <audio> specifications.<br/>
Avneesh Singh: HTML 5 has a broad list.<br/>
Avneesh Singh: I’m wondering why we did not settle on this 5-6 months ago (perhaps longer)?<br/>
… that list was indeed long<br/>
… and I don’t remember what we discussed there previously<br/>
… but we should discuss this with respect to interop, because the list is so huge<br/>
Wendy Reid: I’m trying to find that list<br/>
… what we wanted to avoid was being overly restrictive and being overly broad<br/>
… audio is big, and there are many different codecs<br/>
… and its easier to point to something that’s more up-to-date<br/>
Tzviya Siegman: <a href="https://www.w3.org/TR/html50/embedded-content-0.html#the-audio-element">https://www.w3.org/TR/html50/embedded-content-0.html#the-audio-element</a><br/>
Tzviya Siegman: point being that we can link out to something where its constantly maintained<br/>
Wendy Reid: this is likely more maintainable than ours…and more up to date<br/>
George Kerscher: my only concern is that these hardware players that people buy<br/>
… don’t have every codec in the world on there<br/>
… and they have to license these codecs<br/>
… maybe this isn’t an issue, but distributing to them is something to consider<br/>
Wendy Reid: the hope is to bring this to the existing market<br/>
… mostly audio publishers are distributing in popular formats: MP3, M4A<br/>
… we’re just bringing a unifying process to all this<br/>
… except for the fact that they might be packaged<br/>
… we do realize there will be future codecs<br/>
… and we don’t want to prevent those<br/>
Tzviya Siegman: given the discussion, there’s more to discuss, but are there any objections?<br/>
George Kerscher: no objections<br/>
Laurent Le Meur: Most up to date link : <a href="https://caniuse.com/#feat=audio">https://caniuse.com/#feat=audio</a> + sub-features<br/>
</details>
