### ISSUE TITLE
Audiobooks: The Big Picture

### ISSUE THREAD

**Issue by dauwhe** [w3c/wpub#361]
I'm a little concerned that we haven't talked about the big picture for audiobooks. All our use cases focus on the end-user experience, but we have nothing about distribution. Is our goal really to have native audio books that people listen to with their browsers, and that publishers post on their own websites?  It seems that what we actually want is more like EPUB than WPUB—a discrete bundle of content that is used  as a distribution format, and possibly an end-user format for "reading systems" that might not even be browser-based. Why do you need WebKit if you're only rendering audio? 

What problems are we trying to solve? It seems there might be real problems in distribution, where AFAIK people are just uploading loose audio files and a cover image, and providing metadata separately. 

But I'm also wary of solving problems for an industry that, from some perspectives, is working quite well. What can I tell my audio colleagues at Hachette that will make them want to help us, when people are already listening to our books and sales are growing every year? Is there enough friction in the supply chain that our efforts would be well-received?

**Comment by wareid** [comment]
Hopefully I can shed some light on my thought process and what is guiding me in this adventure, and what I've learned so far.

You're right in that publishers are comfortable with the current system, sending a batch of mp3s with an excel spreadsheet is neither difficult or problematic for them, and as a system in the last few years it has worked. Reading systems, in the rush to capitalize on the growing market have allowed it to continue happening. This is kind of a reverse problem of EPUB where instead of publishers having to get with the program, they've been allowed to lead it. (I am not saying this is a bad thing). 

The current system however is not working for the ecosystem at large. My bias is showing for the user agent side here, who in this equation is experiencing the most issues but the real problems are pushed onto the end user:
- A publisher who provides audio files and a file list has no method of validation for confirming proper track length mapping/file size -- this is left to the UA
- A user would like to download their audiobooks for personal use
- UAs receive and must parse multiple variations of excel track listings
- A user was sent an audiobook by a friend and would like to open it (with the full experience)

There's a reason part of my process here is to see if we can get tools developed from companies as part of this. I understand we will be asking the publishing team at Hachette to do some extra work on the behalf of the retailers, but here are some of the results of fixing the problems above:
- Errors in file mapping and size are caught by an audiopub validator before either a UA or user catch them
- A user is able to download and enjoy their audiobook however they like because they paid for it (no more walled gardens)
- UAs receive consistent files from all publishers, flow of content is smoother
- File sharing! (I know this leads into piracy but who am I to stop this)

**Comment by HadrienGardeur** [comment]
On the contrary, I think that the big picture for audiobooks is very clear.

We're currently in a situation where there is no standard for distribution or for end users and it's problematic in many markets (for instance in France, this is a problem for libraries).

On the distribution side, distributors/retailers/aggregators are expected to be able to handle a myriad of different solutions:

- single track for the whole audiobook
- a bunch of tracks in a directory or a ZIP from which we're supposed to extract metadata directly
- tracks plus spreadsheets from which we're supposed to extract metadata

None of those solutions by the way provide a good solution for even basic publication features like a ToC, we're very much limited to the structure of the files themselves (how the different chapters were divided or not among tracks).
This is far from satisfactory and the whole industry would benefit from a unique packaging format that can be validated and processed properly.

On the end user side, saying that Amazon/Google/Kobo figured out their own solutions is not a valid answer either.
These companies are not the only content distributors in the world and we need an interoperable ecosystem in which users are free to source content wherever they want.

Due to the nature of audio files, it's possible to simply sell a single audio file to a user or zip them up together, which works already in any audio player, but this is not the kind of UX that we expect from a publication (once again, there's no ToC, you won't necessarily get continuous playback and having to unzip first can be very problematic on mobile devices).

Since audiobooks can be huge, distributing a packaged audiobook is not always the ideal solution either when the device or the bandwidth have constraints.

This is why for end users and UAs we need a dual approach in the audiobooks space:

- a streamable format (WP)
- and a packaged format (name still TBD)

In many ways, this feels very similar to the situation for ebooks pre-EPUB, but the requirements are slightly different given the nature of audiobooks.

**Comment by wareid** [comment]
Adding the propose closing as I believe the explainer and our comments have covered this.

**Comment by dauwhe** [comment]
I think the OP gets to close the issue :)
