### ISSUE TITLE
Example for a TOC as JSON in an Audiobook

### ISSUE THREAD

**Issue by HadrienGardeur** [w3c/wpub#369]
As @wareid pointed out during the last Audiobook TF that publishers producing audiobooks do not work with HTML at all, I've created an example to illustrate what a TOC in JSON for an audiobook would potentially look like at https://github.com/w3c/wpub/blob/master/experiments/audiobook/toc-as-json.json

As a point of comparaison, the same example with HTML is also available:

- [Manifest](https://github.com/w3c/wpub/blob/master/experiments/audiobook/flatland.json)
- [TOC](https://github.com/w3c/wpub/blob/master/experiments/audiobook/toc.html)

This is also tied to https://github.com/w3c/wpub/issues/291#issuecomment-438835941

**Comment by rakutenjeff** [comment]
Thanks for awesome example. One thing is I wonder if could add `duration` in each `readingOrder` item (maybe there was already some discussion about if should include duration in readingOrder before...).

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2019/2019-03-18-pwg#section2-15).

- No actions or resolutions
<details><summary><i class="differentiate">View the transcript</i></summary>
2.15. Example for a TOC as JSON in an Audiobooks?<br/>
Wendy Reid: <a href="https://github.com/w3c/wpub/issues/369">https://github.com/w3c/wpub/issues/369</a><br/>
Wendy Reid: #369: Example for a TOC as JSON in an Audiobook<br/>
… HTML is fine as optional and format as specified.<br/>
… won’t always have TOC for audiobooks.<br/>
… Straight audio can cover may not have one.<br/>
… #376 is still open, about encoding manifest.<br/>
… #369 we can close now.<br/>
… close<br/>
</details>
