### ISSUE TITLE
Minor issues on the TOC algorithm

### ISSUE THREAD

**Issue by iherman** [w3c/wpub#379]
Two minor (partially editorial) issues related to the [TOC algorithm](https://w3c.github.io/wpub/#app-toc-structure):

1. How to tell UA what to do when there is no label for a ToC item (null name property or placeholder name?)
2. At the moment, both the [structure](https://w3c.github.io/wpub/#app-toc-html) and the [extraction algorithm](https://w3c.github.io/wpub/#app-toc-ua) are normative. Is it necessary to keep the structure normative or can it be informative?

**Comment by rdeltour** [comment]
> * How to tell UA what to do when there is no label for a ToC item (null name property or placeholder name?)

I believe this depends on what we say about how UAs should/must render the ToC, in 6.3.3 (see also #146).

> * At the moment, both the [structure](https://w3c.github.io/wpub/#app-toc-html) and the [extraction algorithm](https://w3c.github.io/wpub/#app-toc-ua) are normative. Is it necessary to keep the structure normative or can it be informative?

I think keeping both sections as normative is more confusing that helpful, and can be a source of spec bugs. I would rather see the "recommended" content model description as an informative  best practice; this structure section could be moved to _after_ the algorithm description btw.

**Comment by iherman** [comment]
> I believe this depends on what we say about how UAs should/must render the ToC, in 6.3.3 (see also #146).

I do not think the spec would say any _MUST_ as part of the affordances. It may say _SHOULD_-s, though.

**Comment by mattgarrish** [comment]
> I think keeping both sections as normative is more confusing that helpful, and can be a source of spec bugs.

Looking back on it, I don't think the content model is all that easy to understand. It worked for EPUB because EPUB is very strict about the tagging, but now that we're looking for a specific structure within a much more open structure, I'm not sure a content model is an effective way of explaining what we're looking for. I think people will mistake it for the EPUB model, or have difficulty reading that these rules are meant to exist within the nav content model.

I think any risk of bugs will remain even if we rewrite -- because both sections always have to be carefully edited -- but I'd like to try rewriting it to make it more descriptive of what the parsing algorithm is looking for.

**Comment by iherman** [comment]
> Let the user agent fill in the info, like it does with the canonical manifest.

I agree with this, but I do not think the spec should prescribe *what* it should fill it with. It would actually be impossible to do so, in view of the different languages.

**Comment by iherman** [comment]
Can we agree on an approach whereby:

- the structure will be rewritten as a more 'descriptive' and informative text
- there should be a note somewhere at the end of the extraction algorithm (maybe simply in step 5) saying something like:

> If a branch, or the _toc_ itself, does not have an assigned name, the User Agent _MAY_ insert a name of its own choosing.

(Or something like that.)

If so, we can change this issue as an editorial one, and can be solved when @mattgarrish does the editorial changes...

**Comment by TzviyaSiegman** [comment]
@mattgarrish OK to close?
