### ISSUE TITLE
What does "Reading Order" mean in the context of a Web Publication?

### ISSUE THREAD

**Issue by BigBlueHat** [w3c/wpub#38]
Is it merely the action of some supposed "next" and "previous" interface elements?

Is it required to be publication-wide? Or can it be contextual (choose-your-own-adventure)?

If it's contextual, must there only be one "next"?

This relates to musings on #36, but I think has value all on its own. 

I'm also very keen to get input from a wide(r) range of people including those who use Assitive Technology (AT) when reading/listening.

**Comment by baldurbjarnason** [comment]
> Is it merely the action of some supposed "next" and "previous" interface elements?

Not sure if 'merely' is the right term here 😄 but yes, AFAICT, if we are assuming that the ToC is a separate structure (even if it's only separate in the abstract sense) then the primary value is in navigating from primary resource to primary resource in a sequence.

I think contextual or dynamic reading orders (hypertext, wikis, dictionaries, etc.) are better served by having the primary entry point as a single item reading order and then relying on publication-provided navigation for 'next' and 'previous'.

The UA might read 'next' and 'previous' from the publication but if it does so statically (e.g. by reading the HTML instead of the DOM) then it risks doing more harm than good, possibly breaking the publication in a major way. People have been debating hypertext structures and hypertext reading orders for far too long (longer than the web has even existed!) for us to be able to codify a comprehensive solution that will cover all bases.

This approach assumes that UAs will support publication-provided navigation (both gestural and HTML-provided) which is something I've worried in the past that they may not. Epub reading systems, for example, do not support it in any real way. But I'm a little bit more hopeful now.

At the very least, if web publication UAs do provide 'next' and 'previous' navigation features (UI, gestures, keyboard) those should be disabled when there's only one official entry in the reading order so the publication can take over navigation.

**Comment by GarthConboy** [comment]
I'd answer the question "Is it merely the action of some supposed "next" and "previous" interface elements?"

With "It specifies at least the progression of "next" and "previous" interface elements?"  In the general case, allowing progression through the entire publication (or primary resources thereof).

**Comment by iherman** [comment]
@BigBlueHat isn't this issue moot now, with the consensus on #126 (and the PR #142)? If so, this should be closed and its reference removed from the draft.

**Comment by BigBlueHat** [comment]
@iherman PR #142 seems to be about which way the experience of progression flows (ltr/rtl) not about what's being progressed. Meaning, this issue is targeted at the "Default Reading Order" rather than the "Reading Progression Direction."

I'd suggest we leave this open as there's still an open question wrt to several of the new affordance issues as well as things being highlighted by the demos folks are doing (multiple next/previous links, etc).

**Comment by jmulliken** [comment]
I have the same hesitancy to require a reading order. The web makes reading order more ambiguous, and that's some of the reason authors and publishers are embracing it--to challenge the linearity of traditional print. That said, I'm at a loss as to how to convey contents (in a TOC, for example) without implying linearity.

**Comment by pkra** [comment]
@jmulliken wrote
> That said, I'm at a loss as to how to convey contents (in a TOC, for example) without implying linearity.

I'm thinking that if the "TOC" is "just another resource", then it could be any web resource (say, a WebVR experience). People might still happily call it a "Table of Contents" (given that they already say "TOC" despite the fact that those are predominantly just lists).

@dauwhe wrote
> Many, many, many publications do have a linear reading order, and we must make those work.
>  I like Baldur's idea of having at least a single resource in the linear reading order. We have to start somewhere...

:+1:

**Comment by TzviyaSiegman** [comment]
@fbrzvnrnd is it possible that you are thinking of the concept of linear="no" (as described in http://www.idpf.org/epub/30/spec/epub30-publications.html#sec-itemref-elem), which is not the same thing as a default reading order?

**Comment by dauwhe** [comment]
> The default reading order is specified directly in the manifest, but MAY be omitted when it only consists of the primary entry page. When the default reading order is absent, user agents MUST include an entry for the primary entry page when compiling the canonical manifest.

So you don't need to specify a `readingOrder` at all, and it will default to the (required) primary entry page. This just means that the publication author becomes responsible for providing the reader a way of moving between publication resources. So you could do a choose your own adventure book, or a highly nonlinear postmodern novel. We are not preventing authors from doing what they want. We are just trying to support an extremely common use case where there is a linear ordering of primary resources.

**Comment by fbrzvnrnd** [comment]
Thank you for the answers. The explanation of the defualt order in the draft had deceived me. Thank you for the clarifications.

**Comment by wareid** [comment]
Issue of the reading order has achieved consensus.
