### ISSUE TITLE
Optional HTML TOC

### ISSUE THREAD

**Issue by geoffjukes** [w3c/wpub#402]
If the HTML TOC is defined in the manifest, is there any facility for making its use optional? Or does its presence imply it *must* be used?

I can imagine early adopters generating crude TOCs, but not actually caring if they are used.

**Comment by iherman** [comment]
We have not defined, and I am not sure we should, the exact user agent behaviour. That also means that the data is there but the user agent chooses to ignore it, that is fine.

**Comment by llemeurfr** [comment]
@geoffjukes to be precise, the HTML ToC will be referenced from the manifest, not "defined in". It will be represented as a standard HTML resource and this resource will be optional. In the absence of this resource, the user agent (the player) will be able to use the reading order (track listing) as a fallback (this is the current practice). 

I believe that we should describe user agent intended behavior in a best practice document at least.

**Comment by iherman** [comment]
> I believe that we should describe user agent intended behavior in a best practice document at least.

I agree

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2019/2019-03-18-pwg#section2-16).

- No actions or resolutions
<details><summary><i class="differentiate">View the transcript</i></summary>
Optional HTML TOC<br/>
Wendy Reid: <a href="https://github.com/w3c/wpub/issues/402">https://github.com/w3c/wpub/issues/402</a><br/>
Wendy Reid: #402: Optional HTML TOC<br/>
… can close, as we’ve decided on HTML TOC.<br/>
… and be optional.<br/>
… close!<br/>
Avneesh Singh: lots of TOC issues.<br/>
Garth Conboy: Left #376 &amp; #408 for futurue discussions.<br/>
Geoff Jukes: +1 to closing<br/>
Wendy Reid: not dropping topic, but closing just these.<br/>
</details>
