### ISSUE TITLE
Should there be a TOC if supplemental materials are provided in an audio book?

### ISSUE THREAD

**Issue by GeorgeKerscher** [w3c/wpub#408]
We decided that a Table of Contents is not required. We do not expect supplemental materials to be provided in an audio book, such as images, html pages, etc. However, if such supplemental information is provided as resources (not in the reading list/play order), then it would be impossible for the Reading System to do anything predictable with this supplemental material.

Therefore, the question is must a TOC be provided that links to the supplemental materials provided?

I was asked to put this in the issue tracker on Monday March 4, 2019.

**Comment by llemeurfr** [comment]
The Table of Contents is the way for the user to navigate freely in the different sections of the publication. The manifest is the way for the User Agent to know what the publication contains. The manifest does not use the ToC other than for presenting in to the user. 
With the proper `rel` attribute value associated with supplemental material listed in the `resources` section of the manifest, the UA will be able to do something perfectly predictable.
For instance, we can define a `booklet` rel value. The Audiobook UA will discover that and be able to present an "affordance", e.g. a button on the bottom-right of the audiobook cover. Activating the button will open the pdf or html booklet of the audiobook and display it on screen, with a close button. No ToC involved in this UX.

**Comment by iherman** [comment]
@GeorgeKerscher, per the current spec, the constraint we have is that entries added to the ToC must be within the publication's bounds. This includes any resource that is either in the `readingOrder` or in the `resources` lists within the manifest. Ie, if the author has supplementary material that are important information, but he/she does not want to put it into the default reading order, then it should be listed in `resources` and can then be added to the ToC as well.

Ie, I believe there is no problem, but I may not understand the issue...

**Comment by GeorgeKerscher** [comment]
It seems that the question is “must” there be a TOC to access the supplemental resources, or are rel values sufficient to let the user know that there is something (who knows what) there
 
Best
George

**Comment by iherman** [comment]
> It seems that the question is “must” there be a TOC to access the supplemental resources, or are rel values sufficient to let the user know that there is something (who knows what) there

I'd prefer implementers comment on this...

**Comment by HadrienGardeur** [comment]
Here's my take on this:

- while a rel can identify supplemental materials in `resources`, this relies on a UA implementing specific support for it
- on the other hand, every UA should support the TOC, which means that content producers can make sure that supplemental materials are always accessible by the user that way
- but this is very much a best practice regarding authoring, this doesn't feel like something that should be in a specification (aside from examples) and certainly not a MUST

**Comment by wareid** [comment]
Thanks George for logging this! 

I agree with @HadrienGardeur that relying on UAs to implement specific support for a new suite of `rel` values is potentially problematic, whereas TOCs are supported out of the box. 

The spec should address this as an accessibility issue. I would be concerned that leaving it to a best practice gives publishers the opportunity not to include the content in an accessible way (in the TOC). It would be better to recommend that supplemental content outside of the cover be listed in the TOC, and that if that content is present, a content creator SHOULD include a TOC. This leaves it to UAs whether they will support the supplemental content, but it is still visible to the user.

**Comment by llemeurfr** [comment]
> The spec should address this as an accessibility issue. 

@wareid, I don't see how accessibility this connected to this subject. If the UA know what is this the use of this supplemental content and can deal with it, it will do its best for all people, with disabilities or not.  
And if an audiobook UA doesn't support let's say a PDF booklet, having it listed in the ToC won't add much to the equation.  
More, PDF content is often not accessible and nothing in our specs tells anything about it.

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2019/2019-04-08-pwg.html#section2).

- No actions or resolutions
<details><summary><i class="differentiate">View the transcript</i></summary>
Should there be a TOC if supplemental materials are provided in an audio book?<br/>
Wendy Reid: <a href="https://github.com/w3c/wpub/issues/408">https://github.com/w3c/wpub/issues/408</a><br/>
Wendy Reid: issue 408: should there be a TOC? spec says there must be if supplemental content is present in the resources. Any opposition?<br/>
Avneesh Singh: +1<br/>
Garth Conboy: TOC is an ordered list; for many of these supplemental contents there is no specific order<br/>
Wendy Reid: if we don’t put it in the TOC it is not referenceable for a user agent<br/>
Garth Conboy: putting in TOC implies an order that it may not have<br/>
Avneesh Singh: it has some order; not entirely random<br/>
… alt text html file follows dame principle, must be in TOC<br/>
Marisa DeMeglio: reminds me of landmarks in EPUB - not necessarily inherent order<br/>
… don’t agree that supp content needs same treatment as alt content<br/>
Wendy Reid: supp content can be a list of charts or pics of an author<br/>
Avneesh Singh: concept is similar<br/>
Ivan Herman: why is supp material so special that having it listed in the resources is not enough?<br/>
Joshua Pyle: +1 to Ivan<br/>
Bill Kasdorf: +1 to resources<br/>
Wendy Reid: how should resources be represented in reading order?<br/>
George Kerscher: resources always referenced by something; having them in TOC is provides standard mechanism to get at them<br/>
Ivan Herman: resources is a list of references to files, each of which can have one to many rel values<br/>
… from that point on it’s up to the user agent to find<br/>
George Kerscher: is the rel value in the manifest?<br/>
Ivan Herman: yes, and there may be several values as well<br/>
Wendy Reid: See also <a href="https://github.com/w3c/wpub/issues/405">https://github.com/w3c/wpub/issues/405</a><br/>
Brady Duga: want to avoid getting bad audiobook TOCs, prefer it be an optional requirement because reading system may be able to impose its own more accurate TOC<br/>
… TOC should not be required just to have a list of supp materials<br/>
George Kerscher: Brady has a very good point.<br/>
George Kerscher: TOC should be meaningful and something a RS can trust.<br/>
Laurent Le Meur: agreed, for textbooks we have a special rel called cover, that allows us to put it in a TOC or not. if there is a small set of supp content that we always find in audiobooks, let’s use rel values like we use cover<br/>
Wendy Reid: instead of a required TOC of supp content, we require rel value that is applicable to that type of content<br/>
George Kerscher: having a TOC that, when present, is good and utilizable, sounds like putting a requirement on the reading system to use it if present<br/>
Wendy Reid: if the publisher has gone to the effort, it is likely that the reading system should pay attention to it. But can’t define “good” TOC<br/>
Marisa DeMeglio: it might be confusing if treatment is different across reading systems<br/>
Laurent Le Meur: we are living with that with covers currently - reading systems deal with differently<br/>
… if the rel value is not in the TOC, then the reading system won’t see it? Best practice instead of requirement<br/>
Benjamin Young: not necessarily an ordered list; publishers can’t define order if we just have resources floating - needs to be expressible by publishers<br/>
Laurent Le Meur: need to define what is wanted - are there other things besides booklets?<br/>
Benjamin Young: if this is a foundational data model that we are going to share, we may have publications with a whole host of supp content<br/>
Avneesh Singh: if there is an order that publisher want to define for supp content TOC is compulsory<br/>
Ivan Herman: if there is supp content that has an order, there is no need to make TOC is compulsory, because that is what will be used. The toc doesn’t really make sense for content that is not in order. Unnecessary to require TOC “if x and y are true”, for example.<br/>
George Kerscher: consistency between base spec an audiobook spec would be great, as much as possible.<br/>
Brady Duga: the more I hear about potential use cases, the less I think we should use TOC for supp materials, and tackle when we discuss synchronized media<br/>
… textbook and audio appear at the same time, for example<br/>
Marisa DeMeglio: we have an issue currently regarding alternative media, like adding synchronized media to an audiobook (audiobook with text use case)<br/>
Wendy Reid: we should create a mechanism to enable this, but also for when this doesn’t happen<br/>
Marisa DeMeglio: maybe we should have the information in more than one place, even though that can be a bummer for reading systems<br/>
Wendy Reid: will revisit this topic soon<br/>
</details>

**Comment by wareid** [comment]
Discussed in the meeting on June 17, 2019. 

Closing this issue in favour of the discussion on rel values in #405 and will make the requirement for a TOC in audiobooks with supplemental content a SHOULD.

**Comment by iherman** [comment]
This issue was discussed in a meeting.

- `RESOLVED:  Close #408, supplemental content will be identified in the manifest with rel values, and TOCs will be a SHOULD in the spec - best practices to follow`
<details><summary><i class="differentiate">View the transcript</i></summary>
Issue #408: Should there be a TOC if supplemental materials are provided in an audio book?<br/>
Wendy Reid: <a href="https://github.com/w3c/wpub/issues/408">https://github.com/w3c/wpub/issues/408</a><br/>
Wendy Reid: should we require a toc if there’s supplemental material in the audiobook?<br/>
… or so we create a bunch of rel values<br/>
Laurent Le Meur: I’m in favor of closing this issue, and that we will rely on <code>@rel</code><br/>
Wendy Reid: we’d have to create those rel values, right?<br/>
Laurent Le Meur: we need to know which values would be useful<br/>
George Kerscher: I don’t have a problem with <code>@rel</code><br/>
… was the proposal to require a TOC?<br/>
Wendy Reid: the proposal was to require toc if there was supplemental material<br/>
George Kerscher: that’s ok. We do need more work on TOC.<br/>
… toc should be a should :)<br/>
Proposed resolution: Close #408, supplemental content will be identified in the manifest with rel values, and TOCs will be a SHOULD in the spec - best practices to follow (Wendy Reid)<br/>
Wendy Reid: here’s the proposal ^<br/>
Laurent Le Meur: +1<br/>
Luc Audrain: +1<br/>
George Kerscher: +1<br/>
Marisa DeMeglio: +1<br/>
Rachel Comerford: +1<br/>
Charles LaPierre: +1<br/>
Bill Kasdorf: +1<br/>
Resolution #1: Close #408, supplemental content will be identified in the manifest with rel values, and TOCs will be a SHOULD in the spec - best practices to follow<br/>
Luc Audrain: there is an issue about rel values which need to be discussed later<br/>
… and we need rel for cover<br/>
Wendy Reid: we’ll address that as we see what’s needed<br/>
</details>
