### ISSUE TITLE
Language of web publication v. language of manifest/resources

### ISSUE THREAD

**Issue by mattgarrish** [w3c/wpub#53]
According to the infoset, a language should be specified, but it's not entirely clear where the distinction is between the language of the manifest and the language of the publication.

If they are the same thing, it's not possible to express multilingual publications.

If they are not, how is each defined?

For context, see the discussion in PR #51 starting [here](https://github.com/w3c/wpub/pull/51#issuecomment-325158890).

**Comment by iherman** [comment]
(carried over from https://github.com/w3c/wpub/pull/51#issuecomment-325177373)

@mattgarrish,

>>    my feeling is that the language tag is to be meant only for the manifest and the metadata. Ie, it does not have any effect on the individual resources.
>
> Yes, I agree to an extent. The extent being that it has no bearing on any resources, including the manifest.
>

Hm. You made me realize that we have three different roles that we MUST somehow cover.

1. General information on the language(s) of the publication used, e.g., to install or access dictionaries and 
2. Language of the manifest/metadata, ie, the language of textual information like the title (in the manifest) or Dublin Core or schema.org items in the attached metadata
3. Language(s) of the individual resources

I guess we agreed that the language information item has no bearing on No. 3; handling that falls back on how the resources do that per the HTML/SVG/etc. specifications. Maybe we should have, actually, _two_ different language information items for Nos. 1 and 2, with the following extra rules:

* if no publication language is explicitly stated, it has the single "und" value
* if the manifest/metadata language is not stated separately, and there is a single publication language, that one is used; otherwise it has the "und" value

In the absence of a publication language, User Agents MAY reuse the language information of the first primary resource.

**Comment by frivoal** [comment]
Not fully convinced 1 is useful either. UAs could just as well install dictionaries from the actual languages used in the resources, and arguably should do it that way, since that's actually tied to the content.
If it is only used for this kind of meta information not tied to the content, the language in the manifest is just as likely to be wrong: it may end up being set to the default language of the author, for example the UI language of the authoring tool, or copy-pasted from some template and not adjusted to fit the actual content.

For 2, I don't know that a single language will be enough. Various pieces of the manifest data may be in different languages and may need to be tagged separately (e.g. author names).

**Comment by iherman** [comment]
@mattgarrish, isn't this issue moot now? The latest WP draft says that the language information in the infoset is bound to the textual values in the infoset itself, and not related to the language of the resources themselves.

If so, we may want to close the issue (and remove the reference to it from the draft)

**Comment by mattgarrish** [comment]
Weren't we keeping this one open to consider the problem of whether the language of the publication needs a means of expression? If we've decided we're not expressing this information, then I suppose it is moot, but did we decide that?

I don't have a strong take on how important this information actually is, but it was pointed out in the last epub revision when we were discussing the same for dc:language that having the languages available before rendering resources is helpful for pre-loading text-to-speech engines (which are otherwise slow loading for Japanese).

**Comment by HadrienGardeur** [comment]
This is useful for a number of affordances, including:

- TTS (loading the right language/voice)
- dictionary (displaying the most relevant ones, selecting the right default dictionary)
- search (stemming algorithm, stop words and many other operations related to indexing)

**Comment by iherman** [comment]
I am a little bit afraid of the proliferation of information and that it can become a bit confusing. We have now:

* for each textual infoset value we have (potentially) a language and a direction
* a default language and direction that provides a default for the previous
* an overall resource reading direction for the resources

And we are now considering a 

* (default?) language (and, I presume, direction) of the publication's content. (The obvious question would then come about multilingual books.)

There were already confusion on which infoset item is defined for what and things become worse.

I am not sure how to make things clearer, I am just raising a red flag... At the minimum, we should have some decent defaults that would avoid having problems.

**Comment by HadrienGardeur** [comment]
This is consistent with EPUB where:

- language and direction of the members are expressed as [attributes of the package element](https://www.w3.org/Submission/2017/SUBM-epub-packages-20170125/#sec-package-elem)
- individual metadata elements can use the [dir](https://www.w3.org/Submission/2017/SUBM-epub-packages-20170125/#attrdef-dir) and the [xml:lang](https://www.w3.org/Submission/2017/SUBM-epub-packages-20170125/#attrdef-xml-lang) attributes
- language(s) of the publication are [expressed using dc:language in metadata](https://www.w3.org/Submission/2017/SUBM-epub-packages-20170125/#sec-opf-dclanguage)
- reading progression is expressed using [an attribute on the spine element](https://www.w3.org/Submission/2017/SUBM-epub-packages-20170125/#sec-spine-elem)

I don't find it very surprising that we end up with the same infoset.

**Comment by iherman** [comment]
I believe this issue is to be closed: all language related data in the manifest are _for the manifest only_. Propose closing...

Cc @TzviyaSiegman
