### ISSUE TITLE
Should some additional metadata items move to core infoset requirements

### ISSUE THREAD

**Issue by iherman** [w3c/wpub#66]
Section 3.10 of the current draft lists a number of additional metadata items as "should"-s. These may have to be considered as core and listed among the core infoset requirements.

**Comment by iherman** [comment]
The current list in 3.10 includes

> * A list of creators and, optionally, their specific roles. E.g. 'author', 'publisher', 'editor', or 'translator'.
> * Publication date
> * Modification date
> * Accessibility metadata

If these items are "should-s", then the are not really distinguishable from the infoset items listed in  section 3.2.

The question therefore is whether all four items are really to be listed as "should", or some others may be "may".

**Comment by iherman** [comment]
My own feeling is that the list of creators and the accessibility metadata are "should-s", the other two (dates) are 'May'-s alongside the subtitle, licensing information, etc.

**Comment by laudrain** [comment]
With Baldur, Hugh and Boris, we had discussions about those 2 dates and finalize in "SHOULD".
Those dates pertains to the Publication domain:
- without a Pub date, it is not a publication
- without a modification date, there is no mean to know the real date of production (an identical publication may be produced several times)

**Comment by iherman** [comment]
@laudrain: just for the sake of argument, why do you say "without a Pub date, it is not a publication"? I would agree on this for, say, the author, but for the date... if I publish Euclid's elements, then what would be the date? Sure, we could add the date that the publisher uses, but that date may not be really relevant to the content.

Of course, in most of the cases the pub date is important as well as clear, and the WP, ehem, MAY include that as part of the information set. But the SHOULD seems to be too strong.

The modification date is even weaker. Of course, it may be useful and important, so it MAY be part of the information set. But that case is weaker than a SHOULD.

(Although, honestly, we are knit picking here. If all four are set to be SHOULD, we could live with that. But then these items do not differ from the main list of information set and should be moved there imho.)

**Comment by BigBlueHat** [comment]
I agree with @laudrain (and friends) that it'd be great to have some "publication" signal, but perhaps that's a separate issue?

**Comment by iherman** [comment]
@BigBlueHat I think it is. We should not make a metadata element a 'signal' imho.

**Comment by TzviyaSiegman** [comment]
I don't think the date should be the signal. I think we should create a separate issue for published status or something like that.

**Comment by laudrain** [comment]
**@iherman** as I already mentioned in previous discussions, IMO, the event of making a WP public is inherent to the notion of Publication. This event is related to the creator effort to author and gather content as a whole, the result being a work, be it manifested in a Web Publication.

If it is a Publication, it doesn't exist publicly before the Publication Date, and afterwards, it will be referenced as "the work from X titled "N" published at date Z".
Otherwise, it is a Web site with no reference in time.

Even if we don't know precisely the date of "appearance" of the work, it is always stated in time: "Euclid's elements" are form c. 300 BC, Wikipedia says. You would never imagine a Publication without a date, even if it is controversial. 
Other example: would you imagine a news article without a date?

That said, as for other info, this date may be calculated form the production process if the creator doesn't give it explicitly.

@all I don't see this as a 'signal' neither imho.

The modification date is also IMHO important even if it is more technical. A WP published at Z may have been tweacked for any reason without changing the work content. It is still the same manifestation but do you read the latest version?
We know this well in ebook world: our EPUBs have been technically changed at least a handfull of time after publication. Without modification date, no tracking is possible for the reader or the user agent. We also have use cases where this is critical for legal issues.

**Comment by iherman** [comment]
@laudrain, I won't lie down the road on this:-) If the general feeling is that a publication date is a SHOULD, be it.

The modification date... for me this remains less convincing. Of course, there are cases (legal issues as you mention) where this is clearly not even a SHOULD but a MUST, but we are talking about a general case.

If I take a W3C publication: there is indeed a publication date in the header (ie, roughly, the metadata) but there is no such thing as a modification date. The date itself varies often.

Bug again, I am fine going with the flow, the difference between SHOULD and MAY is not all that significant.

**Comment by baldurbjarnason** [comment]
What switched me from may to should on modification date is that it becomes a very important piece of metadata in a portable context (any sort of portability: syndication, federation, packaged, etc.). It might even become a MUST in a PWP. So, in my view it's a should because that way we increase the odds of any given web publication becoming a functional portable web publication when converted.

However, I also see a rationale for pushing it to a MAY to maximise the ease of creating a web publication.

**Comment by iherman** [comment]
As agreed on the meeting of 2017-09-25, closing the issue
