### ISSUE TITLE
Publication memory

### ISSUE THREAD

**Issue by mattgarrish** [w3c/wpub#77]
Reading a publication is not as simple as getting a manifest and adding some reading enhancements to the current page. The reading experience has to persist between page loads, for example.

The manifest cannot be unloaded from the user agent's memory if every resource is not required to have a link to it, for example, otherwise the publication is lost. There also has to be at least some memory that the user has already accepted to initiate the publication so they aren't prompted over and over. And every top-level document has to be in the resource list for the scope of the publication to be established and maintained if links are optional.

Similarly, what happens behind the scenes to make direct access to a manifest work needs detail. I assume the user agent parses the manifest into memory, unloads the document, retains memory of it and load the first document in the reading order.

Also, if not every resource links to the manifest, a user could come back to the page they left off reading and not be able to initiate the publication they were in. There would need to be a new kind of bookmarking that retains publication memory, but even that is imperfect as people often just pull documents back up from their history.

Maybe this more a comment that there is more to the lifecycle than just initiating and updating a publication, and there are a lot of complexities in trying to be very flexible to all scenarios.

We at least need to cover scope and persistence issues, if not fully define them.

**Comment by lrosenthol** [comment]
On Sun, Oct 1, 2017 at 10:38 AM, Matt Garrish <notifications@github.com>
wrote:

> Reading a publication is not as simple as getting a manifest and adding
> some reading enhancements to the current page. The reading experience has
> to persist between page loads, for example.
>
That's UA business logic and has nothing to do with the standard, IMO.
There are good reasons for a UA to persist such information and there are
good reasons not to - it's not our place to require (or even suggest).


> The manifest cannot be unloaded from the user agent's memory if every
> resource is not required to have a link to it, for example, otherwise the
> publication is lost.
>
Again, you are designing products here - that's not our province or goal.


> Similarly, what happens behind the scenes to make direct access to a
> manifest work needs detail.
>
No, it does not.  That is entirely up to the UA based on its design
criteria.


> Maybe this more a comment that there is more to the lifecycle than just
> initiating and updating a publication, and there are a lot of complexities
> in trying to be very flexible to all scenarios.
>
Which is just another reason why we should leave this out of scope.

**Comment by baldurbjarnason** [comment]
You're right that persistence is a hairy problem. Which is why I strongly prefer us to avoid it altogether if at all possible—even if that compromises some of the user experience.

The only way you can reasonably get proper persistence is through some sort of defined install process coupled with a pre-defined UI/UX. And if we do that, we need a _really_ good reason to explain why we couldn't just reuse the web platform's pre-existing persistent actors (Service Workers and Web App Manifests). And even if we _do_ have really good reasons, we're still going to alienate a bunch of browser vendors because it _will_ compromise their ability to integrate web publications into their products.

And that's a risk that isn't limited to browser vendors, if we go into too much detail on how UAs should handle persistence, UI, and navigation, we run the considerable risk of preventing a bunch of potential constituencies and interests from implementing publication support in their products. That could compromise the format's viability even before it exists.

My suggestion—if we decide that this is needed (I'm not convinced)—would be to punt the persistence question to a later, standalone, specification and leave the behaviour undefined and UA-specific for now. That later specification could then define how persistence in various different contexts. And we could base that spec on how implementations turn out.

***

Like @lrosenthol I question the idea that defining this is in our province. How a UA initiates the publication is likely vary wildly from context to context.

Bespoke reading apps, browsers, web-based reading services, library apps, all are likely to have substantially different behaviour that we simply can't cover in a single spec and we run a considerable risk of accidentally making a bunch of use cases impossible if we try to define a single behaviour.

To venture into the _hypothetical_, while most of us are familiar with how a bespoke reading app would work, behaviour in a browser or browser-like context is likely to be quite different.

In those contexts the entire experience is likely to be partly stateless by requiring every resource that wants to initiate publication behaviour to link to the manifest. The prompting to initiate 'publication mode' could just work in a similar way as location API prompts do. The UA remembers the answer for any given origin for X amount of time. If the user arrives at a resource that links to a manifest, the UI for that manifest is automatically loaded if the user as approved publication behaviour within a vendor-defined period of time. The UA also keeps the publication UI for navigations as long as they are to other resources within the publication but that UI is ephemeral and will disappear from pages that don't link to the manifest in subsequent sessions.

This _hypothetical_ behaviour would a reasonable expectation considering how browsers behave today. But not all browsers would behave this way. And it would be unreasonable of us to expect non-browser UAs to copy this behaviour. By specifying this or some other behaviour we either force everybody into the same User Experience or (more likely) we simply rule out implementations in contexts where this behaviour isn't the norm or isn't desirable or may even cost a vendor valuable users.

***

In any case, if we manage to work within the confines of the web app manifest we then get 'installed and persistent' behaviour in the browser context for free. The web app manifest already lets developers give UI hints that persist across the app.

If we _can't_ work within the confines of the web app manifest then we have a pretty big problem on our hands as we'd almost certainly be giving browser vendors a strong disincentive to support publications. But that's a separate issue altogether.


***

### My personal conclusion:

I don't see how we'd benefit from bringing this into scope at this stage. It lands squarely into an area of behaviour where User Agents are likely to want to differentiate themselves from other implementations to better serve their specific customer base. We could solve some of this as a side-effect of using web app manifests if we go down that route.

But even if we don't go the app manifest route we're still better off only tackling this question at a later date. When we have actual implementations specifying what behaviour they all share will be a much easier of handling this problem.

**Comment by dauwhe** [comment]
> When we have actual implementations specifying what behaviour they all share will be a much easier of handling this problem.

Do you think we'd benefit by focusing on a "data model" sort of spec, and only define the serialization of the information which will be needed for script, user agents, or standalone reading systems to provide useful user experiences?

If we have that, then we can polyfill with service worker, and start figuring out what works and what doesn't.

**Comment by lrosenthol** [comment]
On Sun, Oct 1, 2017 at 3:43 PM, Dave Cramer <notifications@github.com>
wrote:

> Do you think we'd benefit by focusing on a "data model" sort of spec,
>
> I don't think so - because that's all going to be either publication or UA
specific.    (remember that a publication can choose to implement some/all
of this themselves if they wish a specific experience regardless of UA)

**Comment by mattgarrish** [comment]
> That's UA business logic and has nothing to do with the standard, IMO.

Then why are we even venturing into obtaining and processing the manifest, or prompting to initiate? What is that but business logic? If we're defining that, we can't avoid what happens when a manifest is directly loaded.

I'd rather we didn't try to spec out this level of detail, as I agree there won't be one common UA, but if we do then it opens up a lot of problems.

Regardless, though, there still needs to be some reasonable model for how a publication is understood by a user agent. That detail is still lacking as far as I can see, as the UA can't rely on links to the manifest or the manifest being complete.

It gets back to the bounds/scope of the publication. That information needs to be available through links and/or patchable through the resource list or else it leaves holes in authoring/implementation for authors and UAs.

**Comment by lrosenthol** [comment]
On Sun, Oct 1, 2017 at 4:24 PM, Matt Garrish <notifications@github.com>
wrote:

> That's UA business logic and has nothing to do with the standard, IMO.
>
> Then why are we even venturing into obtaining and processing the manifest,
> or prompting to initiate?
>
I have no idea.  That, as you say, is also business logic and not relevant.

Unless we think there is something special about how a UA would obtain this
manifest, but I don't see what that is...



> Regardless, though, there still needs to be some reasonable model for how
> a publication is understood by a user agent.
>
To a certain extent, yes.  But how much (or little) is still under debate
amongst ourselves - so it's clearly way too early to go down this path
(IMO).


> It gets back to the bounds/scope of the publication.
>
Yes, which we can't agree on...


> That information needs to be available through links and/or patchable
> through the resource list or else it leaves holes in
> authoring/implementation for authors and UAs.
>
 You lost me on this one...

**Comment by mattgarrish** [comment]
> I have no idea.  That, as you say, is also business logic and not relevant.

It is to HTML and Web App, though. Both define processes for obtaining the external resources, and in the case of Web App for installing. The advantage of both is that they have specific user agents in mind. Here we don't

I'm not convinced Web Apps solves any of our specific needs, but it does make me wonder how little we can specify and still expect the specification to be taken seriously by browsers.

As Dave says, we probably should move to more of a data model approach if we're punting on UA specifics (or anything more than what can be used as fallback data).

>> That information needs to be available through links and/or patchable
 through the resource list or else it leaves holes in
 authoring/implementation for authors and UAs.

> You lost me on this one...

There has to be some reliable way of establishing the bounds of what belongs to the publication. Currently, it's not the default reading order, the resource list or linking, although all play a role.

All I believe we need here is a statement that any resources not listed in the resource list are considered external to the publication. A user agent can then cross-reference the resource list if it encounters an unlinked resource not in the default reading order.

**Comment by iherman** [comment]
@dauwhe,

>>    When we have actual implementations specifying what behaviour they all share will be a much easier of handling this problem.
>
>Do you think we'd benefit by focusing on a "data model" sort of spec, and only define the serialization of the information which will be needed for script, user agents, or standalone reading systems to provide useful user experiences?
>
>If we have that, then we can polyfill with service worker, and start figuring out what works and what doesn't.

I was put off, at first, by the terminology you used:-( "Data Model" first made me think that we would define some sort of a DOM of DOM-s, which would be a complicated task.

But, if what you propose is that we consider a "UA driven" approach, with a purely hypothetical UA, and what we would standardize is what is *needed* to fulfill the various requirements (**_without specifying the "how"_**) then I think I agree. If I consider what has been done so far for the PWD actually does fit into the picture, but it does indeed question whole "lifecycle" section. Maybe we can be without it... (at least for now).

As an example for a UA driven view is the whole question of EPUBCFI-like specification. If we consider a long form and non-paginated view of a publication, then having a means to store bookmarks in a flexible way (and without a load on the authors) does lead to the need of something like EPUBCFI. Ie, we may need to specify something like that.

**Comment by dauwhe** [comment]
> But, if what you propose is that we consider a "UA driven" approach, with a purely hypothetical UA, and what we would standardize is what is needed to fulfill the various requirements (without specifying the "how") then I think I agree.

Yes, that's it :)

**Comment by mattgarrish** [comment]
> what is needed to fulfill the various requirements (without specifying the "how")

This is how I read it.

Having struggled with section 5, without a specific user agent in mind, it's very hard to write steps that need to be followed. Whether the UA is an embedded script, an app, a browser or something else has implications on how initiation of a web app occurs.

Just to go back to what I was getting at above, what a browser has to do when a manifest file is loaded (parse and load the first file) is probably different than what an epub-like reading system would do (add to a bookshelf and let the user decide what next).

We can try to chart out what user agents could do in all these scenarios, but it might be better to wait and see what models emerge before trying for this level of standardization, if we attempt at all.

**Comment by mattgarrish** [comment]
Closing as discussed on the 2017-10-02 telecon as we're not going to spend time on these lifecycle issues and instead focus on a info-driven generic UA approach.
