### ISSUE TITLE
Security: Can a WP contain JavaScript?

### ISSUE THREAD

**Issue by lrosenthol** [w3c/wpub#90]
Certainly a lot of malicious content and exploits can be prevented if JS execution is disallowed by default, or even not permitted in the file itself.

However, JavaScript execution is fundamental to the OWP. Disallowing JavaScript would considerably cut down the power of WP.

AMP also restricts some JS features for similar reasons

**Comment by baldurbjarnason** [comment]
For regular, non-portable web publications that are hosted on the publisher's domain (or that of a trusted distributor)? Sure. It's basically a website with added features.

For portable web publications however, it gets complicated.

There's always going to be tension between portability and security. The web's security model is based on DNS, TLS and locations, and packaging does away with all three. I don't see how JS execution can be unfettered in portable web publications _unless_ we have a robust method for package/resource signing tied to the HTTPS/TLS public-key system. 

Funnily enough, the reason why people in the WG don't want to use web packaging—it requires all resources to have an http location—is exactly the reason why it is more compatible with the web's security model than the alternatives. It lends itself more easily for tighter coupling with the TLS public-key system. (AFAICT, I may well be getting things wrong about what's going on with web packaging.)

As I understand it, the web packaging work is aiming to have something along these lines—a security model based on TLS signing—but since the WG seems to be moving away from using that work, we're probably going to have to outline some security limitations for JS in portable web publications. And make it clear that UAs may opt to disallow JS in portable files for security reasons.

So, my two cents on the question in the issue's title:

- Yes, a WP can contain JS but in a _portable_ context many UAs will either not execute any JS or impose limitations on its execution context.

**Comment by baldurbjarnason** [comment]
The AMP reference is interesting as their model is to disallow all JS that isn't delivered via a pre-defined library of custom components. That model is dependent on a set of community-developed custom elements.

**Comment by baldurbjarnason** [comment]
And before people pull browser extensions into this, modern browsers rely on a _whitelist_ for extensions in addition to pretty harsh CSP-style restrictions. I.e. they have to be vetted and delivered through their own stores to be executed. You can turn on a 'developer mode' in most cases to bypass these restrictions but as a whole, this system isn't something that can scale to accommodate open publishing ecosystems.

**Comment by baldurbjarnason** [comment]
I don't think we can do much more in the spec than just say that many UAs will choose to restrict PWP JS based on their trust in the packaging format, provenance, and own execution architecture. 

Some parts of the ecosystem or community may come up with their own tactics for mitigating this (e.g. whitelisted JS libraries a la AMP) or extensions to the packaging format. I think, for example, a community curated whitelist of safe JS libraries that can be used via HTML (as opposed to inline code)—that is, code triggered by class/data- attributes or custom elements—might work well in the open education space. 

Some sectors may even settle on AMP itself as a requirement for scripted interactivity as it's become a fairly capable format in its own right.

Other sectors may need different solutions but I'm not sure we can predefine those solutions.

Of course, many of these issues go away if the packaging format supports origin-based signing that is natively supported by the UA.

(Apologies for spamming the issue. It's either this or spamming the TPAC IRC channel.)

**Comment by lrosenthol** [comment]
@baldurbjarnason Agreed on all your points - thanks!   As we decided in the meeting, we will allow all features of the OWP in a WP.  When we get to PWP and EPUB4, that may change.
